#:schema https://yazi-rs.github.io/schemas/keymap.json

# Keep only local overrides here; all other bindings are inherited from Yazi.

[[mgr.prepend_keymap]]
on   = "M"
run  = "plugin mount"
desc = "Open mount manager"

[[mgr.prepend_keymap]]
on   = "<Right>"
run  = "plugin smart-enter"
desc = "Enter directory or open file"

[[mgr.prepend_keymap]]
on = "y"
run = [
  'shell -- if [ -n "$WAYLAND_DISPLAY" ]; then for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list; else printf "%s\n" "$@" | dclip; fi',
  "yank",
]
desc = "Yank and copy paths to the system clipboard"

[[mgr.prepend_keymap]]
on   = "f"
run  = "plugin smart-filter"
desc = "Filter continuously and enter a unique directory"

[[mgr.prepend_keymap]]
on   = ["g", "p"]
run  = "cd ~/projects"
desc = "Go to ~/projects"

[[mgr.prepend_keymap]]
on   = ["g", "a"]
run  = "cd ~/dotfiles"
desc = "Go to ~/dotfiles"

[[mgr.prepend_keymap]]
on   = ["g", "d"]
run  = "cd ~/Documents"
desc = "Go to ~/Documents"

[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"
