"""A zsh completion script for one command tree.

The shape follows what clap_complete emits for the rust tools, so both halves
of this repository complete the same way: one function per command path,
`_arguments` for the flags, `_describe` for the subcommands, and the `funcstack`
guard at the end so the script works whether it is sourced or autoloaded.

Values that only the tool knows are not baked in. They become a helper that
asks the tool at the moment the cursor is on that argument, which keeps the
script static and still correct after a profile or a host is added.
"""

from tools.surface import pages, prose, spec

SHELLS = ("zsh",)

# Flags that answer instead of running the command, so nothing else applies.
EXCLUSIVE_OF_EVERYTHING = "(- *)"


def script(tree, program=""):
    program = program or tree.name
    helpers = {}
    functions = [_function(command, program, helpers) for command in tree.walk()]
    guard = _guard(program)
    parts = [
        f"#compdef {program}",
        "",
        f"# Generated by `{program} --completions zsh`; edits are lost on the next sync.",
        "",
        *functions,
        *[helpers[name] for name in sorted(helpers)],
        guard,
    ]
    return "\n".join(parts)


def _guard(program):
    # Sourced from a startup file the script has to register itself; autoloaded
    # from fpath it is called directly. clap_complete emits the same test.
    return (
        f'if [ "$funcstack[1]" = "_{program}" ]; then\n'
        f'    _{program} "$@"\n'
        "else\n"
        f"    compdef _{program} {program}\n"
        "fi\n"
    )


def _name(command):
    return "_" + "__".join(command.path)


def _function(command, program, helpers):
    specs = _option_specs(command, program, helpers) + _argument_specs(command, program, helpers)
    children = command.visible()
    # Only the root dispatches: `dotfile secret <name>` never becomes an exec.
    dispatched = pages.dispatched(program) if command.path == (program,) else ()
    body = [f"{_name(command)}() {{"]
    if children or dispatched:
        body.append("    local context state state_descr line ret=1")
        body.append("    typeset -A opt_args")
        specs = specs + ["'1: :->command'", "'*:: :->argument'"]
        body.append(_arguments("-s -S -C", specs))
        body.append("    case $state in")
        body.append("        command)")
        body.append(_commands_block(command, dispatched))
        body.append("            ;;")
        body.append("        argument)")
        body.append("            case $line[1] in")
        for child in children:
            body.append(f"                {child.name}) {_name(child)} && ret=0 ;;")
        for name, binary in dispatched:
            # `*:: :->argument` has already re-shifted words and CURRENT, which
            # is what the tool's own function expects; the guard keeps the
            # branch inert where that tool is not installed.
            body.append(
                f"                {name}) (( $+functions[_{binary}] )) && _{binary} && ret=0 ;;"
            )
        body.append("            esac")
        body.append("            ;;")
        body.append("    esac")
        body.append("    return ret")
    else:
        body.append("    local ret=1")
        body.append("    typeset -A opt_args")
        body.append(_arguments("-s -S", specs))
        body.append("    return ret")
    body.append("}")
    body.append("")
    return "\n".join(body)


def _arguments(flags, specs):
    if not specs:
        return "    _arguments " + flags + " && ret=0"
    joined = " \\\n        ".join(specs)
    return f"    _arguments {flags} \\\n        {joined} && ret=0"


def _commands_block(command, dispatched=()):
    items = ["            local -a commands", "            commands=("]
    for child in command.visible():
        items.append(f"                {_quote(child.name + ':' + _describe_text(child.help))}")
    for name, binary in dispatched:
        described = _describe_text(prose.COMMANDS.get(binary, ""))
        items.append(f"                {_quote(name + ':' + described)}")
    items.append("            )")
    label = _quote(f"{command.label} command")
    items.append(f"            _describe -t commands {label} commands && ret=0")
    return "\n".join(items)


def _option_specs(command, program, helpers):
    sources = spec.values_for(command.label)
    groups = spec.exclusive_for(command.label)
    specs = []
    for param in command.options():
        if param.hidden:
            continue
        specs.extend(_option(command, param, sources, groups, program, helpers))
    if not any(param.flag == "--help" for param in command.options()):
        specs.append(f"'{EXCLUSIVE_OF_EVERYTHING}--help[Show this message and exit.]'")
    return specs


def _option(command, param, sources, groups, program, helpers):
    spellings = param.opts + param.secondary
    if param.standard:
        exclusion = EXCLUSIVE_OF_EVERYTHING
    elif param.multiple:
        exclusion = ""
    else:
        exclusion = _exclusion(spellings, groups)
    star = "*" if param.multiple else ""
    described = _bracket(param.help)
    action = _action(command, param, sources, program, helpers)
    specs = []
    for spelling in spellings:
        if param.takes_value:
            suffix = "=" if spelling.startswith("--") else "+"
            tag = _describe_text(param.name.replace("_", "-"))
            body = f"{star}{exclusion}{spelling}{suffix}{described}:{tag}:{action}"
        else:
            body = f"{star}{exclusion}{spelling}{described}"
        specs.append(f"'{_quote_body(body)}'")
    return specs


def _exclusion(spellings, groups):
    excluded = set(spellings)
    for group in groups:
        if excluded & set(group):
            excluded |= set(group)
    return "(" + " ".join(sorted(excluded)) + ")"


def _argument_specs(command, program, helpers):
    sources = spec.values_for(command.label)
    specs = []
    position = 0
    for param in command.arguments():
        if param.hidden:
            continue
        position += 1
        tag = _describe_text(param.name.replace("_", "-"))
        action = _action(command, param, sources, program, helpers)
        index = "*" if param.multiple else str(position)
        separator = ":" if param.required or param.multiple else "::"
        specs.append(f"'{_quote_body(f'{index}{separator}{tag}:{action}')}'")
    return specs


def _action(command, param, sources, program="", helpers=None):
    if param.flag == "--completions":
        return "(" + " ".join(SHELLS) + ")"
    source = sources.get(param.flag if param.kind == "option" else param.name)
    if source is None:
        # A value with nothing to suggest: the message still shows what it is.
        return ""
    if source.kind == "choices":
        return "(" + " ".join(source.options()) + ")"
    if source.kind == "commas":
        return f"_values -s , {source.tag} " + " ".join(source.options())
    if source.kind == "files":
        return f'_files -g "{source.pattern}"' if source.pattern else "_files"
    if source.kind == "dirs":
        return "_files -/"
    if source.kind in ("call", "pair") and helpers is not None:
        return _helper(source, program, helpers)
    if source.kind in ("call", "pair"):
        return ""
    return ""


def _helper(source, program, helpers):
    stem = source.tag if source.kind == "pair" else source.values[0]
    name = f"_{program}_complete_" + "".join(
        character if character.isalnum() else "_" for character in stem
    )
    if name not in helpers:
        helpers[name] = (
            _pair_helper(name, source, program)
            if source.kind == "pair"
            else (_call_helper(name, source, program))
        )
    return name


def _call_helper(name, source, program):
    return (
        f"{name}() {{\n"
        "    local -a items\n"
        f'    items=(${{(f)"$(_call_program {program}-values'
        f' {program} __complete {source.values[0]} 2>/dev/null)"}})\n'
        "    (( $#items )) || return 1\n"
        f"    _describe -t values {_quote(source.tag)} items\n"
        "}\n"
    )


def _pair_helper(name, source, program):
    groups, names = source.values
    return (
        f"{name}() {{\n"
        "    local -a items\n"
        "    if compset -P '*='; then\n"
        f'        items=(${{(f)"$(_call_program {program}-values'
        f' {program} __complete {names} ${{IPREFIX%=}} 2>/dev/null)"}})\n'
        f"        _describe -t values {_quote(source.tag)} items\n"
        "    else\n"
        f'        items=(${{(f)"$(_call_program {program}-values'
        f' {program} __complete {groups} 2>/dev/null)"}})\n'
        "        _describe -t values 'group' items -S '=' -q\n"
        "    fi\n"
        "}\n"
    )


def _bracket(text):
    """A flag's description, as `_arguments` wants it: inside square brackets."""
    described = _describe_text(text)
    return f"[{described}]" if described else ""


def _describe_text(text):
    """Help text with everything zsh would read as syntax taken out of it."""
    flat = " ".join((text or "").split())
    for character, replacement in (("\\", r"\\"), (":", r"\:"), ("[", r"\["), ("]", r"\]")):
        flat = flat.replace(character, replacement)
    return flat


def _quote_body(text):
    return text.replace("'", "'\\''")


def _quote(text):
    return "'" + _quote_body(text) + "'"


def known_shell(shell):
    return shell in SHELLS
