[package]
name              = "doc-purge"
version           = "0.1.0"
description       = "Purge comments, doc strings and typographic glyphs from source files"
edition.workspace = true
license.workspace = true

[dependencies]
clap.workspace        = true
rayon.workspace       = true
workstation.workspace = true

[dev-dependencies]
tempfile.workspace = true