[package]
name              = "doc-purge"
version.workspace = true
description       = "Purge comments, doc strings and typographic glyphs from source files"
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
clap.workspace  = true
rayon.workspace = true
workstation     = { workspace = true, features = ["walk"] }

[dev-dependencies]
testkit.workspace = true