use std::collections::BTreeMap;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

mod lua;
mod render;
mod text;

pub const PACKAGES: &[&str] = &[
    "hyprland", "kde", "nvim", "tmux", "vscode", "wezterm", "yazi", "zsh",
];
pub const INPUTS: &[&str] = &["shared", "macos", "linux"];
pub const MARKER: &str = "<!-- Generated by doc-keybinds; edit the source configuration. -->";

#[derive(Clone, Debug, Default, Eq, PartialEq, Ord, PartialOrd)]
pub struct Binding {
    pub context: String,
    pub key: String,
    pub action: String,
    pub description: String,
    pub source: String,
    pub line: usize,
}

#[derive(Default)]
pub struct Package {
    pub bindings: Vec<Binding>,
    pub settings: Vec<Binding>,
    pub sources: Vec<String>,
}

pub fn root(requested: Option<PathBuf>) -> Result<PathBuf, String> {
    let chosen = requested
        .or_else(|| std::env::var_os("DOTFILE_ROOT").map(PathBuf::from))
        .or_else(|| {
            std::env::current_dir().ok().and_then(|cwd| {
                cwd.ancestors()
                    .find(|p| p.join("config/targets.dotfile").is_file())
                    .map(Path::to_path_buf)
            })
        })
        .unwrap_or_else(|| Path::new(env!("CARGO_MANIFEST_DIR")).join("../../../.."));
    if !chosen.join("config/targets.dotfile").is_file() {
        return Err(format!(
            "{}: dotfiles repository not found",
            chosen.display()
        ));
    }
    chosen
        .canonicalize()
        .map_err(|e| format!("{}: {e}", chosen.display()))
}

pub fn collect(root: &Path) -> Result<BTreeMap<String, Package>, String> {
    let mut packages: BTreeMap<String, Package> = PACKAGES
        .iter()
        .map(|p| (p.to_string(), Package::default()))
        .collect();
    let mut files = Vec::new();
    for input in INPUTS {
        walk(root, &root.join(input), &mut files)?;
    }
    files.sort();
    let mut sources = BTreeMap::new();
    for path in files {
        let name = path
            .strip_prefix(root)
            .map_err(|e| e.to_string())?
            .to_string_lossy()
            .replace('\\', "/");
        if let Some(package) = classify(&name) {
            let body = fs::read_to_string(&path).map_err(|e| format!("{name}: {e}"))?;
            packages
                .get_mut(package)
                .unwrap()
                .sources
                .push(name.clone());
            sources.insert(name, (package, body));
        }
    }
    let variables = text::hypr_variables(
        sources
            .iter()
            .filter(|(_, (p, _))| *p == "hyprland")
            .map(|(_, (_, s))| s.as_str()),
    );
    for (source, (name, body)) in &sources {
        let package = packages.get_mut(*name).unwrap();
        let result = match *name {
            "wezterm" | "nvim" => lua::parse(source, body, name, &sources, package),
            "tmux" => text::tmux(source, body, package),
            "zsh" => text::zsh(source, body, package),
            "hyprland" => text::hyprland(source, body, &variables, package),
            "kde" => text::kde(source, body, package),
            "vscode" => text::vscode(source, body, package),
            "yazi" => text::yazi(source, body, package),
            _ => unreachable!(),
        };
        result.map_err(|e| format!("{source}: {e}"))?;
    }
    let tmux = packages["tmux"].bindings.clone();
    for binding in &mut packages.get_mut("wezterm").unwrap().bindings {
        if let Some(args) = binding.action.strip_prefix("tmux.dispatch(")
            && binding.description == lua::describe(&binding.action)
        {
            let target = serde_json::Deserializer::from_str(args)
                .into_iter::<String>()
                .next()
                .and_then(Result::ok);
            if let Some(target) = target {
                let target = target.strip_suffix("Arrow").unwrap_or(&target);
                let descriptions: std::collections::BTreeSet<_> = tmux
                    .iter()
                    .filter(|b| b.key == target && b.context.starts_with("prefix"))
                    .map(|b| b.description.as_str())
                    .collect();
                let fallback = args
                    .split_once(',')
                    .map(|(_, s)| lua::describe(s.trim().strip_suffix(')').unwrap_or(s.trim())))
                    .unwrap_or_default();
                let target = if descriptions.is_empty() {
                    format!("prefix {target}")
                } else {
                    descriptions.into_iter().collect::<Vec<_>>().join(" / ")
                };
                binding.description = format!("Tmux: {target}; WezTerm: {fallback}");
            }
        }
    }
    for package in packages.values_mut() {
        package.bindings.sort();
        package.bindings.dedup();
        package.settings.sort();
        package.settings.dedup();
    }
    Ok(packages)
}

fn classify(name: &str) -> Option<&'static str> {
    let parts: Vec<_> = name.split('/').collect();
    let has = |p| parts.contains(&p);
    if has("tests") || has("_types") {
        return None;
    }
    if has("wezterm") && name.ends_with(".lua") {
        return Some("wezterm");
    }
    if has("nvim") && name.ends_with(".lua") {
        return Some("nvim");
    }
    if has("tmux") && name.ends_with(".conf") {
        return Some("tmux");
    }
    if has("zsh") && (name.ends_with(".zsh") || name.ends_with("/.zshrc")) {
        return Some("zsh");
    }
    if has("hypr") && name.ends_with(".conf") {
        return Some("hyprland");
    }
    if name.ends_with("/kglobalshortcutsrc") {
        return Some("kde");
    }
    if has("vscode")
        && (name.ends_with("/keybindings.json") || name.ends_with("/keybindings.jsonc"))
    {
        return Some("vscode");
    }
    if has("yazi") && name.ends_with("/keymap.toml") && !has("plugins") {
        return Some("yazi");
    }
    None
}

fn walk(root: &Path, dir: &Path, files: &mut Vec<PathBuf>) -> Result<(), String> {
    if !dir.exists() {
        return Ok(());
    }
    for entry in fs::read_dir(dir).map_err(|e| format!("{}: {e}", dir.display()))? {
        let entry = entry.map_err(|e| e.to_string())?;
        let kind = entry.file_type().map_err(|e| e.to_string())?;
        if kind.is_symlink() {
            continue;
        }
        let path = entry.path();
        let name = entry.file_name();
        if kind.is_dir() {
            if matches!(
                name.to_str(),
                Some(".git" | "node_modules" | "target" | ".venv" | "tests")
            ) {
                continue;
            }
            // Yazi plugins are vendored defaults, not local keymap declarations.
            if name == "plugins"
                && path
                    .strip_prefix(root)
                    .unwrap()
                    .components()
                    .any(|c| c.as_os_str() == "yazi")
            {
                continue;
            }
            walk(root, &path, files)?;
        } else if kind.is_file() {
            files.push(path);
        }
    }
    Ok(())
}

pub fn generate(root: &Path, check: bool) -> Result<Vec<PathBuf>, String> {
    let packages = collect(root)?;
    let pages = render::pages(&packages);
    let directory = root.join("docs/keybinds");
    let mut changes = Vec::new();
    for (name, body) in &pages {
        let path = directory.join(name);
        match fs::read_to_string(&path) {
            Ok(old) if old == *body => continue,
            Ok(_) => {}
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
            Err(e) => return Err(format!("{}: {e}", path.display())),
        }
        changes.push((path, Some(body)));
    }
    if directory.exists() {
        for entry in fs::read_dir(&directory).map_err(|e| e.to_string())? {
            let entry = entry.map_err(|e| e.to_string())?;
            let path = entry.path();
            if !entry.file_type().map_err(|e| e.to_string())?.is_file()
                || path.extension().is_none_or(|e| e != "md")
                || pages.contains_key(&entry.file_name().to_string_lossy().to_string())
            {
                continue;
            }
            let body = fs::read_to_string(&path).map_err(|e| format!("{}: {e}", path.display()))?;
            if body.lines().any(|line| line == MARKER) {
                changes.push((path, None));
            }
        }
    }
    changes.sort_by(|a, b| a.0.cmp(&b.0));
    if !check && !changes.is_empty() {
        fs::create_dir_all(&directory).map_err(|e| e.to_string())?;
        for (path, body) in &changes {
            if let Some(body) = body {
                let mut file =
                    tempfile::NamedTempFile::new_in(&directory).map_err(|e| e.to_string())?;
                file.write_all(body.as_bytes()).map_err(|e| e.to_string())?;
                file.persist(path)
                    .map_err(|e| format!("{}: {e}", path.display()))?;
            } else {
                fs::remove_file(path).map_err(|e| format!("{}: {e}", path.display()))?;
            }
        }
    }
    Ok(changes
        .into_iter()
        .map(|(path, _)| path.strip_prefix(root).unwrap().to_path_buf())
        .collect())
}

pub(crate) fn compact(s: &str) -> String {
    s.split_whitespace().collect::<Vec<_>>().join(" ")
}

pub(crate) fn humanize(s: &str) -> String {
    let mut result = String::new();
    let mut previous = ' ';
    for c in s.chars() {
        if c.is_uppercase() && previous.is_lowercase() {
            result.push(' ');
        }
        result.push(if matches!(c, '_' | '-' | '.') { ' ' } else { c });
        previous = c;
    }
    let result = compact(&result);
    let mut chars = result.chars();
    chars
        .next()
        .map(|c| c.to_uppercase().to_string() + chars.as_str())
        .unwrap_or_default()
}
