add_newline = false

format = '$python$git_branch$directory$character'

right_format = '$cmd_duration'

[python]
format = '([$symbol\($virtualenv\)]($style))'
symbol = ' '
style = 'yellow'
detect_extensions = []
detect_files = []
detect_folders = []

[git_branch]
format = '[\[$branch\]]($style)'
style = 'green'

[directory]
format = '[\[$path\]]($style)'
style = 'cyan'
truncation_length = 8
truncate_to_repo = false

[cmd_duration]
min_time = 2000
format = 'took [$duration]($style)'
style = 'yellow'

[character]
success_symbol = '[\$](bold)'
error_symbol = '[\$](bold)'
