-- Generated by dotfile theme from theme/profiles/sexy-purple.toml — do not edit.
local active = require "ui.colors.sexy-purple"

local profiles = {
  "latte",
  "mocha",
  "sexy-purple",
}

---@class GeneratedThemePalette
---@field foreground string
---@field background string
---@field cursor_bg string
---@field cursor_fg string
---@field cursor_border string
---@field selection_fg string
---@field selection_bg string
---@field ansi string[]
---@field brights string[]

---@class GeneratedThemeConfig
---@field color_schemes? table<string, GeneratedThemePalette>
---@field color_scheme? string

local M = {}

---@return GeneratedThemePalette
function M.get_active()
  return active.colors
end

---@param config GeneratedThemeConfig
function M.apply_to_config(config)
  local schemes = {}
  for _, profile in ipairs(profiles) do
    local scheme = require("ui.colors." .. profile)
    schemes[scheme.name] = scheme.colors
  end
  config.color_schemes = schemes
  config.color_scheme = active.name
end

return M
