-- Generated by dotfile theme from theme/profiles/sexy-purple.toml — do not edit.
local profiles = {
  "latte",
  "mocha",
  "sexy-purple",
}

local M = {}

function M.apply_to_config(config)
  local schemes = {}
  for _, profile in ipairs(profiles) do
    local scheme = require("ui.colors." .. profile)
    schemes[scheme.name] = scheme.colors
  end
  config.color_schemes = schemes
  config.color_scheme = "Sexy Purple"
end

return M
