-- Generated by dotfile theme from theme/profiles/sexy-purple.toml — do not edit.
return {
  name = "Sexy Purple",
  colors = {
    foreground = "#ffffff",
    background = "#15152b",
    cursor_bg = "#ffffff",
    cursor_fg = "#15152b",
    cursor_border = "#ffffff",
    selection_fg = "#ffffff",
    selection_bg = "#380d6a",
    ansi = { "#3b4252", "#bf616a", "#a3be8c", "#ebcb8b", "#81a1c1", "#b48ead", "#88c0d0", "#e5e9f0" },
    brights = { "#4c566a", "#bf616a", "#a3be8c", "#ebcb8b", "#81a1c1", "#b48ead", "#8fbcbb", "#eceff4" },
  },
}
