import os
import tomllib

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
THEME_DIR = os.path.join(ROOT, "theme")
MAPS_DIR = os.path.join(THEME_DIR, "maps")
TEMPLATES_DIR = os.path.join(THEME_DIR, "templates")

GENERATED_HEADER = "Generated by scripts/generate-theme.py from theme/palette.toml — do not edit."


def path(*parts):
    return os.path.join(ROOT, *parts)


def load_toml(target):
    with open(target, "rb") as handle:
        return tomllib.load(handle)


def load_map(name):
    return load_toml(os.path.join(MAPS_DIR, f"{name}.toml"))


def load_template(name):
    with open(os.path.join(TEMPLATES_DIR, name), encoding="utf-8") as handle:
        return handle.read()


class Theme:
    def __init__(self, palette_data, font_data):
        self.data = palette_data
        self.palette = palette_data["palette"]
        self.fonts = font_data["fonts"]
        self.font_applications = font_data.get("applications", {})

    @classmethod
    def load(cls):
        return cls(
            load_toml(os.path.join(THEME_DIR, "palette.toml")),
            load_toml(os.path.join(THEME_DIR, "fonts.toml")),
        )

    def hex(self, name):
        try:
            return self.palette[name].lower()
        except KeyError:
            raise SystemExit(f"unknown palette color: {name}")

    def role(self, name):
        try:
            return self.hex(self.data["roles"][name])
        except KeyError:
            raise SystemExit(f"unknown role: {name}")

    def kde(self, name):
        try:
            return self.hex(self.data["kde"][name])
        except KeyError:
            raise SystemExit(f"unknown kde role: {name}")

    def color(self, name):
        if name in self.data.get("kde", {}):
            return self.kde(name)
        return self.hex(name)

    def font(self, name):
        try:
            return self.fonts[name]
        except KeyError:
            raise SystemExit(f"unknown font role: {name}")

    def uses_fonts(self, application):
        enabled = self.font_applications.get(application, False)
        if not isinstance(enabled, bool):
            raise SystemExit(f"font application setting must be true or false: {application}")
        return enabled

    def rgb(self, value):
        digits = value.lstrip("#")
        return int(digits[0:2], 16), int(digits[2:4], 16), int(digits[4:6], 16)

    def rgb_csv(self, value):
        return "{},{},{}".format(*self.rgb(value))

    def truecolor(self, value, bold=False):
        red, green, blue = self.rgb(value)
        prefix = "1;" if bold else ""
        return f"\\u001b[{prefix}38;2;{red};{green};{blue}m"

    def ansi(self, value):
        return "38;2;{};{};{}".format(*self.rgb(value))
