use std::collections::BTreeMap;
use std::path::Path;

use super::metadata::{self, Command, Param};
use crate::context::Context;
use clap_complete::Shell;

type Helpers = BTreeMap<String, String>;

pub fn emit(shell: Shell) -> Result<(), String> {
    if shell != Shell::Zsh {
        return Err(format!("no {shell} completions; available: zsh"));
    }
    print!("{}", script(&metadata::native()));
    Ok(())
}
pub fn write_all(context: &Context, directory: &Path) -> Result<usize, String> {
    let python = metadata::python(context)?;
    if !python.commands.is_empty()
        && python.source_fingerprint != metadata::python_fingerprint(context)?
    {
        return Err("Python command metadata is stale; run ./setup.sh --commands-only".into());
    }
    if python.commands.is_empty() && context.root.join("scripts/python/src/tools").is_dir() {
        return Err("Python command metadata missing; run ./setup.sh --commands-only".into());
    }
    let mut scripts = python.completions;
    scripts.insert("dotfile".into(), script(&metadata::native()));
    let count = scripts.len();
    let body = scripts.into_values().collect::<Vec<_>>().join("\n");
    crate::fs::write_generated(&directory.join("tools-completion.zsh"), body.as_bytes())?;
    Ok(count)
}
pub fn script(tree: &Command) -> String {
    let mut helpers = Helpers::new();
    let mut parts =
        vec!["#compdef dotfile\n\n# Generated by `dotfile --completions zsh`.\n".to_string()];
    for command in tree.walk() {
        parts.push(function(command, &mut helpers));
    }
    parts.extend(helpers.into_values());
    parts.push("if [ \"$funcstack[1]\" = \"_dotfile\" ]; then\n    _dotfile \"$@\"\nelse\n    compdef _dotfile dotfile\nfi\n".into());
    parts.join("\n")
}
fn name(c: &Command) -> String {
    format!("_{}", c.path.join("__"))
}
fn describe(s: &str) -> String {
    s.split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
        .replace('\\', "\\\\")
        .replace(':', "\\:")
        .replace('[', "\\[")
        .replace(']', "\\]")
}
fn quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}
fn arguments(specs: &[String], children: bool) -> String {
    let flags = if children { "-s -S -C" } else { "-s -S" };
    if specs.is_empty() {
        return format!("    _arguments {flags} && ret=0");
    }
    format!(
        "    _arguments {flags} \\\n        {} && ret=0",
        specs.join(" \\\n        ")
    )
}
fn function(c: &Command, helpers: &mut Helpers) -> String {
    let mut specs = Vec::new();
    let mut position = 0;
    for p in &c.params {
        if p.hidden {
            continue;
        }
        let action = action(c, p, helpers);
        let tag = describe(&p.name.replace('_', "-"));
        if p.kind == "option" {
            let spellings = p
                .opts
                .iter()
                .chain(&p.secondary)
                .cloned()
                .collect::<Vec<_>>();
            let exclusion = if p.standard() {
                "(- *)".to_string()
            } else if p.multiple {
                String::new()
            } else {
                let mut excluded = spellings.clone();
                excluded.extend(p.conflicts.iter().cloned());
                excluded.sort();
                excluded.dedup();
                format!("({})", excluded.join(" "))
            };
            let star = if p.multiple { "*" } else { "" };
            let help = describe(&p.help);
            let help = if help.is_empty() {
                help
            } else {
                format!("[{help}]")
            };
            for spelling in &spellings {
                let body = if p.metavar.is_empty() {
                    format!("{star}{exclusion}{spelling}{help}")
                } else {
                    let suffix = if spelling.starts_with("--") { "=" } else { "+" };
                    format!("{star}{exclusion}{spelling}{suffix}{help}:{tag}:{action}")
                };
                specs.push(quote(&body));
            }
        } else {
            position += 1;
            let index = if p.multiple {
                "*".into()
            } else {
                position.to_string()
            };
            let sep = if p.required || p.multiple { ":" } else { "::" };
            specs.push(quote(&format!("{index}{sep}{tag}:{action}")));
        }
    }
    let children = c
        .children
        .iter()
        .filter(|c| !c.hidden && c.name() != "help")
        .collect::<Vec<_>>();
    let root = c.path.len() == 1;
    let mut lines = vec![
        format!("{}() {{", name(c)),
        "    local context state state_descr line ret=1".into(),
        "    typeset -A opt_args".into(),
    ];
    if !children.is_empty() || root {
        specs.extend(["'1: :->command'".into(), "'*:: :->argument'".into()]);
        lines.push(arguments(&specs, true));
        lines.extend([
            "    case $state in".into(),
            "        command)".into(),
            "            local -a commands".into(),
            "            commands=(".into(),
        ]);
        for child in &children {
            lines.push(format!(
                "                {}",
                quote(&format!("{}:{}", child.name(), describe(&child.help)))
            ));
        }
        if root {
            lines.push("                'format:Format configured files'".into());
        }
        lines.extend([
            "            )".into(),
            format!(
                "            _describe -t commands {} commands && ret=0",
                quote(&format!("{} command", c.label()))
            ),
            "            ;;".into(),
            "        argument)".into(),
            "            case $line[1] in".into(),
        ]);
        for child in &children {
            lines.push(format!(
                "                {}) {} && ret=0 ;;",
                child.name(),
                name(child)
            ));
        }
        if root {
            lines.push("                format) (( $+functions[_dotfile-format] )) && _dotfile-format && ret=0 ;;".into());
        }
        lines.extend([
            "            esac".into(),
            "            ;;".into(),
            "    esac".into(),
        ]);
    } else {
        lines.push(arguments(&specs, false));
    }
    lines.extend(["    return ret".into(), "}\n".into()]);
    lines.join("\n")
}
fn action(c: &Command, p: &Param, helpers: &mut Helpers) -> String {
    if p.flag() == "--completions" {
        return "(zsh)".into();
    }
    let label = c.label();
    let key = if p.kind == "option" {
        p.flag()
    } else {
        &p.name
    };
    let source = match key {
        "profile" if label.starts_with("dotfile theme") => Some("theme-profiles"),
        "profile" => Some("profiles"),
        "scope" if label.starts_with("dotfile theme") => Some("theme-scopes"),
        "--to" => Some("hosts"),
        "--pkg" if label.starts_with("dotfile dev") => Some("dev-packages"),
        "--lang" if label.starts_with("dotfile dev") => Some("dev-languages"),
        "--pkg" => Some("packages"),
        "label" if label.starts_with("dotfile secret") => Some("recipients"),
        "path" if label == "dotfile remove" => Some("tracked"),
        "path" if label == "dotfile secret edit" => Some("secrets"),
        "path" if label == "dotfile system diff" => Some("system-files"),
        _ => None,
    };
    if let Some(source) = source {
        return helper(source, helpers);
    }
    if key == "--override" {
        let name = "_dotfile_complete_override";
        helpers.entry(name.into()).or_insert_with(||format!("{name}() {{\n    local -a items\n    if compset -P '*='; then\n        items=(${{(f)\"$(_call_program dotfile-values dotfile __complete override-names ${{IPREFIX%=}} 2>/dev/null)\"}})\n        _describe -t values 'override' items\n    else\n        items=(${{(f)\"$(_call_program dotfile-values dotfile __complete override-groups 2>/dev/null)\"}})\n        _describe -t values 'group' items -S '=' -q\n    fi\n}}\n"));
        return name.into();
    }
    if !p.choices.is_empty() {
        return format!(
            "({})",
            p.choices
                .iter()
                .map(|s| quote(s))
                .collect::<Vec<_>>()
                .join(" ")
        );
    }
    match key {
        "--using" => "_files -g \"*.txt\"".into(),
        "path" | "paths" => "_files".into(),
        "--group" => format!("({})", crate::artifacts::packages::DEFAULT_GROUPS.join(" ")),
        _ => String::new(),
    }
}
fn helper(source: &str, helpers: &mut Helpers) -> String {
    let name = format!("_dotfile_complete_{}", source.replace('-', "_"));
    helpers.entry(name.clone()).or_insert_with(||format!("{name}() {{\n    local -a items\n    items=(${{(f)\"$(_call_program dotfile-values dotfile __complete {source} 2>/dev/null)\"}})\n    (( $#items )) || return 1\n    _describe -t values '{source}' items\n}}\n"));
    name
}
