keypress_delay_ms: 20
keymap:
  - name: Literal backtick
    remap:
      Shift-Equal: [Shift-Equal, Space]
  - name: Konsole and kitty copy and interrupt
    application:
      only: /(?i)^(org\.kde\.konsole|kitty)$/
    exact_match: true
    remap:
      Ctrl-C: Ctrl-Shift-C
      Ctrl-X: Ctrl-C
  - name: Clean paste
    remap:
      Ctrl-Shift-V:
        - launch: ["/bin/sh", "-c", "$HOME/dotfiles/scripts/.venv/bin/clean-paste"]
        - sleep: 200
        - Ctrl-Shift-V
