#![forbid(unsafe_code)]

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

mod lua;
mod render;
mod text;

pub const PACKAGES: &[&str] = &[
    "hyprland", "kde", "nvim", "vscode", "wezterm", "yazi", "zsh",
];
pub const MARKER: &str = "<!-- Generated by dotfile docs; edit the source configuration. -->";

#[derive(Clone, Debug, Default, Eq, PartialEq, Ord, PartialOrd)]
pub struct Binding {
    pub context: String,
    pub key: String,
    pub action: String,
    pub description: String,
    pub source: String,
    pub line: usize,
}

#[derive(Default)]
pub struct Package {
    pub bindings: Vec<Binding>,
    pub settings: Vec<Binding>,
    pub sources: Vec<String>,
}

pub fn collect(root: &Path) -> Result<BTreeMap<String, Package>, String> {
    let mut packages: BTreeMap<String, Package> = PACKAGES
        .iter()
        .map(|p| (p.to_string(), Package::default()))
        .collect();
    let mut files = Vec::new();
    for group in [root.join("shared"), root.join("macos")] {
        discover_group(root, &group, &mut files)?;
    }
    for group in directories(&root.join("linux"))? {
        discover_group(root, &group, &mut files)?;
    }
    files.sort();
    let mut sources = BTreeMap::new();
    for path in files {
        let name = path
            .strip_prefix(root)
            .map_err(|e| e.to_string())?
            .to_string_lossy()
            .replace('\\', "/");
        if let Some(package) = classify(&name) {
            let body = fs::read_to_string(&path).map_err(|e| format!("{name}: {e}"))?;
            packages
                .get_mut(package)
                .unwrap()
                .sources
                .push(name.clone());
            sources.insert(name, (package, body));
        }
    }
    let variables = text::hypr_variables(
        sources
            .iter()
            .filter(|(_, (p, _))| *p == "hyprland")
            .map(|(_, (_, s))| s.as_str()),
    );
    for (source, (name, body)) in &sources {
        let package = packages.get_mut(*name).unwrap();
        let result = match *name {
            "wezterm" | "nvim" => lua::parse(source, body, name, &sources, package),
            "zsh" => text::zsh(source, body, package),
            "hyprland" => text::hyprland(source, body, &variables, package),
            "kde" => text::kde(source, body, package),
            "vscode" => text::vscode(source, body, package),
            "yazi" => text::yazi(source, body, package),
            _ => unreachable!(),
        };
        result.map_err(|e| format!("{source}: {e}"))?;
    }
    for package in packages.values_mut() {
        package.bindings.sort();
        package.bindings.dedup();
        package.settings.sort();
        package.settings.dedup();
    }
    Ok(packages)
}

fn classify(name: &str) -> Option<&'static str> {
    let parts: Vec<_> = name.split('/').collect();
    let has = |p| parts.contains(&p);
    if has("tests") || has("_types") {
        return None;
    }
    if has("wezterm") && name.ends_with(".lua") {
        return Some("wezterm");
    }
    if has("nvim") && name.ends_with(".lua") {
        return Some("nvim");
    }
    if has("zsh") && (name.ends_with(".zsh") || name.ends_with("/.zshrc")) {
        return Some("zsh");
    }
    if has("hypr") && name.ends_with(".conf") {
        return Some("hyprland");
    }
    if name.ends_with("/kglobalshortcutsrc") {
        return Some("kde");
    }
    if has("vscode")
        && (name.ends_with("/keybindings.json") || name.ends_with("/keybindings.jsonc"))
    {
        return Some("vscode");
    }
    if has("yazi") && name.ends_with("/keymap.toml") && !has("plugins") {
        return Some("yazi");
    }
    None
}

fn directories(path: &Path) -> Result<Vec<PathBuf>, String> {
    let entries = match fs::read_dir(path) {
        Ok(entries) => entries,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(Vec::new()),
        Err(error) => return Err(format!("{}: {error}", path.display())),
    };
    let mut found = Vec::new();
    for entry in entries {
        let entry = entry.map_err(|error| error.to_string())?;
        if entry
            .file_type()
            .map_err(|error| error.to_string())?
            .is_dir()
        {
            found.push(entry.path());
        }
    }
    found.sort();
    Ok(found)
}

fn discover_group(root: &Path, group: &Path, files: &mut Vec<PathBuf>) -> Result<(), String> {
    for package in directories(group)? {
        let name = package
            .file_name()
            .and_then(|name| name.to_str())
            .unwrap_or("");
        if name == "overrides" {
            for variant in directories(&package)? {
                discover_group(root, &variant, files)?;
            }
        } else if matches!(
            name,
            "hypr" | "kde" | "plasma" | "nvim" | "vscode" | "wezterm" | "yazi" | "zsh"
        ) {
            walk(root, &package, files)?;
        }
    }
    Ok(())
}

fn walk(root: &Path, dir: &Path, files: &mut Vec<PathBuf>) -> Result<(), String> {
    if !dir.exists() {
        return Ok(());
    }
    for entry in fs::read_dir(dir).map_err(|e| format!("{}: {e}", dir.display()))? {
        let entry = entry.map_err(|e| e.to_string())?;
        let kind = entry.file_type().map_err(|e| e.to_string())?;
        if kind.is_symlink() {
            continue;
        }
        let path = entry.path();
        let name = entry.file_name();
        if kind.is_dir() {
            if matches!(
                name.to_str(),
                Some(".git" | "node_modules" | "target" | ".venv" | "tests" | "_types")
            ) {
                continue;
            }
            // Yazi plugins are vendored defaults, not local keymap declarations.
            if name == "plugins"
                && path
                    .strip_prefix(root)
                    .unwrap()
                    .components()
                    .any(|c| c.as_os_str() == "yazi")
            {
                continue;
            }
            walk(root, &path, files)?;
        } else if kind.is_file()
            && classify(
                &path
                    .strip_prefix(root)
                    .map_err(|error| error.to_string())?
                    .to_string_lossy(),
            )
            .is_some()
        {
            files.push(path);
        }
    }
    Ok(())
}

pub(super) fn outputs(root: &Path) -> Result<Vec<super::plan::Output>, String> {
    let packages = collect(root)?;
    let pages = render::pages(&packages);
    let directory = root.join("docs/keybinds");
    let mut outputs = Vec::new();
    for (name, body) in &pages {
        let relative = Path::new("docs/keybinds").join(name);
        let path = root.join(&relative);
        let old = super::plan::read(&path)?;
        if !old.is_empty() && !owned(&old) {
            return Err(format!("{}: generated marker missing", relative.display()));
        }
        outputs.push(super::plan::Output::text(relative, body.clone()));
    }
    if directory.exists() {
        for entry in fs::read_dir(&directory).map_err(|e| e.to_string())? {
            let entry = entry.map_err(|e| e.to_string())?;
            let path = entry.path();
            if !entry.file_type().map_err(|e| e.to_string())?.is_file()
                || path.extension().is_none_or(|e| e != "md")
                || pages.contains_key(&entry.file_name().to_string_lossy().to_string())
            {
                continue;
            }
            if owned(&super::plan::read(&path)?) {
                outputs.push(super::plan::Output::remove(
                    path.strip_prefix(root).unwrap().to_path_buf(),
                ));
            }
        }
    }
    Ok(outputs)
}

fn owned(body: &str) -> bool {
    body.lines().any(|line| line == MARKER)
}

pub(crate) fn compact(s: &str) -> String {
    s.split_whitespace().collect::<Vec<_>>().join(" ")
}

pub(crate) fn humanize(s: &str) -> String {
    let mut result = String::new();
    let mut previous = ' ';
    for c in s.chars() {
        if c.is_uppercase() && previous.is_lowercase() {
            result.push(' ');
        }
        result.push(if matches!(c, '_' | '-' | '.') { ' ' } else { c });
        previous = c;
    }
    let result = compact(&result);
    let mut chars = result.chars();
    chars
        .next()
        .map(|c| c.to_uppercase().to_string() + chars.as_str())
        .unwrap_or_default()
}
