[colors]
"borders"                                             = "surface_alt"
"content_view_bg"                                     = "view_bg"
"error_color"                                         = "negative"
"error_color_backdrop"                                = "negative"
"error_color_insensitive"                             = "border"
"error_color_insensitive_backdrop"                    = "border"
"insensitive_base_color"                              = "panel"
"insensitive_base_fg_color"                           = "separator"
"insensitive_bg_color"                                = "panel"
"insensitive_borders"                                 = "surface"
"insensitive_fg_color"                                = "separator"
"insensitive_selected_bg_color"                       = "surface_alt"
"insensitive_selected_fg_color"                       = "separator"
"insensitive_unfocused_bg_color"                      = "panel"
"insensitive_unfocused_fg_color"                      = "separator"
"insensitive_unfocused_selected_bg_color"             = "surface_alt"
"insensitive_unfocused_selected_fg_color"             = "separator"
"link_color"                                          = "link"
"link_visited_color"                                  = "visited"
"success_color"                                       = "positive"
"success_color_backdrop"                              = "positive"
"success_color_insensitive"                           = "border"
"success_color_insensitive_backdrop"                  = "border"
"theme_base_color"                                    = "view_bg"
"theme_bg_color"                                      = "window_bg"
"theme_button_background_backdrop"                    = "button_bg"
"theme_button_background_backdrop_insensitive"        = "surface"
"theme_button_background_insensitive"                 = "surface"
"theme_button_background_normal"                      = "button_bg"
"theme_button_decoration_focus"                       = "decoration"
"theme_button_decoration_focus_backdrop"              = "decoration"
"theme_button_decoration_focus_backdrop_insensitive"  = "border"
"theme_button_decoration_focus_insensitive"           = "border"
"theme_button_decoration_hover"                       = "decoration"
"theme_button_decoration_hover_backdrop"              = "decoration"
"theme_button_decoration_hover_backdrop_insensitive"  = "border"
"theme_button_decoration_hover_insensitive"           = "border"
"theme_button_foreground_active"                      = "foreground"
"theme_button_foreground_active_backdrop"             = "foreground"
"theme_button_foreground_active_backdrop_insensitive" = "separator"
"theme_button_foreground_active_insensitive"          = "separator"
"theme_button_foreground_backdrop"                    = "foreground"
"theme_button_foreground_backdrop_insensitive"        = "separator"
"theme_button_foreground_insensitive"                 = "separator"
"theme_button_foreground_normal"                      = "foreground"
"theme_fg_color"                                      = "foreground"
"theme_header_background"                             = "header_bg"
"theme_header_background_backdrop"                    = "header_alt"
"theme_header_background_light"                       = "header_alt"
"theme_header_foreground"                             = "foreground"
"theme_header_foreground_backdrop"                    = "foreground"
"theme_header_foreground_insensitive"                 = "separator"
"theme_header_foreground_insensitive_backdrop"        = "separator"
"theme_hovering_selected_bg_color"                    = "selection_bg"
"theme_selected_bg_color"                             = "selection_bg"
"theme_selected_fg_color"                             = "selection_fg"
"theme_text_color"                                    = "foreground"
"theme_titlebar_background"                           = "header_bg"
"theme_titlebar_background_backdrop"                  = "header_alt"
"theme_titlebar_background_light"                     = "header_alt"
"theme_titlebar_foreground"                           = "foreground"
"theme_titlebar_foreground_backdrop"                  = "foreground"
"theme_titlebar_foreground_insensitive"               = "separator"
"theme_titlebar_foreground_insensitive_backdrop"      = "separator"
"theme_unfocused_base_color"                          = "view_bg"
"theme_unfocused_bg_color"                            = "window_bg"
"theme_unfocused_fg_color"                            = "foreground"
"theme_unfocused_selected_bg_color"                   = "selection_bg"
"theme_unfocused_selected_bg_color_alt"               = "selection_bg"
"theme_unfocused_selected_fg_color"                   = "selection_fg"
"theme_unfocused_text_color"                          = "foreground"
"theme_unfocused_view_bg_color"                       = "view_bg"
"theme_unfocused_view_text_color"                     = "separator"
"theme_view_active_decoration_color"                  = "decoration"
"theme_view_hover_decoration_color"                   = "decoration"
"tooltip_background"                                  = "tooltip_bg"
"tooltip_border"                                      = "border"
"tooltip_text"                                        = "foreground"
"unfocused_borders"                                   = "surface_alt"
"unfocused_insensitive_borders"                       = "surface"
"warning_color"                                       = "neutral"
"warning_color_backdrop"                              = "neutral"
"warning_color_insensitive"                           = "border"
"warning_color_insensitive_backdrop"                  = "border"