[colors]
"borders"                                             = "border_on_canvas"
"content_view_bg"                                     = "view_bg"
"error_color"                                         = "error_text_on_canvas"
"error_color_backdrop"                                = "error_text_on_canvas"
"error_color_insensitive"                             = "disabled_on_canvas"
"error_color_insensitive_backdrop"                    = "disabled_on_canvas"
"insensitive_base_color"                              = "panel_bg"
"insensitive_base_fg_color"                           = "disabled_on_panel"
"insensitive_bg_color"                                = "panel_bg"
"insensitive_borders"                                 = "border_on_panel"
"insensitive_fg_color"                                = "disabled_on_panel"
"insensitive_selected_bg_color"                       = "surface"
"insensitive_selected_fg_color"                       = "disabled_on_surface"
"insensitive_unfocused_bg_color"                      = "panel_bg"
"insensitive_unfocused_fg_color"                      = "disabled_on_panel"
"insensitive_unfocused_selected_bg_color"             = "surface"
"insensitive_unfocused_selected_fg_color"             = "disabled_on_surface"
"link_color"                                          = "info_text_on_canvas"
"link_visited_color"                                  = "ansi_magenta_text_on_canvas"
"success_color"                                       = "success_text_on_canvas"
"success_color_backdrop"                              = "success_text_on_canvas"
"success_color_insensitive"                           = "disabled_on_canvas"
"success_color_insensitive_backdrop"                  = "disabled_on_canvas"
"theme_base_color"                                    = "view_bg"
"theme_bg_color"                                      = "window_bg"
"theme_button_background_backdrop"                    = "button_bg"
"theme_button_background_backdrop_insensitive"        = "surface"
"theme_button_background_insensitive"                 = "surface"
"theme_button_background_normal"                      = "button_bg"
"theme_button_decoration_focus"                       = "focus_ring_on_surface"
"theme_button_decoration_focus_backdrop"              = "focus_ring_on_surface"
"theme_button_decoration_focus_backdrop_insensitive"  = "border_on_surface"
"theme_button_decoration_focus_insensitive"           = "border_on_surface"
"theme_button_decoration_hover"                       = "focus_ring_on_surface"
"theme_button_decoration_hover_backdrop"              = "focus_ring_on_surface"
"theme_button_decoration_hover_backdrop_insensitive"  = "border_on_surface"
"theme_button_decoration_hover_insensitive"           = "border_on_surface"
"theme_button_foreground_active"                      = "text_on_surface"
"theme_button_foreground_active_backdrop"             = "text_on_surface"
"theme_button_foreground_active_backdrop_insensitive" = "disabled_on_surface"
"theme_button_foreground_active_insensitive"          = "disabled_on_surface"
"theme_button_foreground_backdrop"                    = "text_on_surface"
"theme_button_foreground_backdrop_insensitive"        = "disabled_on_surface"
"theme_button_foreground_insensitive"                 = "disabled_on_surface"
"theme_button_foreground_normal"                      = "text_on_surface"
"theme_fg_color"                                      = "text_on_canvas"
"theme_header_background"                             = "header_bg"
"theme_header_background_backdrop"                    = "header_alt"
"theme_header_background_light"                       = "header_alt"
"theme_header_foreground"                             = "text_on_panel"
"theme_header_foreground_backdrop"                    = "text_on_panel"
"theme_header_foreground_insensitive"                 = "disabled_on_panel"
"theme_header_foreground_insensitive_backdrop"        = "disabled_on_panel"
"theme_hovering_selected_bg_color"                    = "selection_bg"
"theme_selected_bg_color"                             = "selection_bg"
"theme_selected_fg_color"                             = "selection_fg"
"theme_text_color"                                    = "text_on_canvas"
"theme_titlebar_background"                           = "header_bg"
"theme_titlebar_background_backdrop"                  = "header_alt"
"theme_titlebar_background_light"                     = "header_alt"
"theme_titlebar_foreground"                           = "text_on_panel"
"theme_titlebar_foreground_backdrop"                  = "text_on_panel"
"theme_titlebar_foreground_insensitive"               = "disabled_on_panel"
"theme_titlebar_foreground_insensitive_backdrop"      = "disabled_on_panel"
"theme_unfocused_base_color"                          = "view_bg"
"theme_unfocused_bg_color"                            = "window_bg"
"theme_unfocused_fg_color"                            = "text_on_canvas"
"theme_unfocused_selected_bg_color"                   = "selection_bg"
"theme_unfocused_selected_bg_color_alt"               = "selection_bg"
"theme_unfocused_selected_fg_color"                   = "selection_fg"
"theme_unfocused_text_color"                          = "text_on_canvas"
"theme_unfocused_view_bg_color"                       = "view_bg"
"theme_unfocused_view_text_color"                     = "disabled_on_canvas"
"theme_view_active_decoration_color"                  = "focus_ring"
"theme_view_hover_decoration_color"                   = "focus_ring"
"tooltip_background"                                  = "tooltip_bg"
"tooltip_border"                                      = "border_on_surface"
"tooltip_text"                                        = "text_on_surface"
"unfocused_borders"                                   = "border_on_canvas"
"unfocused_insensitive_borders"                       = "surface"
"warning_color"                                       = "warning_text_on_canvas"
"warning_color_backdrop"                              = "warning_text_on_canvas"
"warning_color_insensitive"                           = "disabled_on_canvas"
"warning_color_insensitive_backdrop"                  = "disabled_on_canvas"