[groups]
"Colors:Window"           = ["window_bg", "window_alt"]
"Colors:Button"           = ["button_bg", "button_alt"]
"Colors:View"             = ["view_bg", "view_alt"]
"Colors:Tooltip"          = ["tooltip_bg", "tooltip_alt"]
"Colors:Complementary"    = ["window_bg", "window_alt"]
"Colors:Header"           = ["header_bg", "header_alt"]
"Colors:Header][Inactive" = ["window_bg", "window_alt"]
"Colors:Selection"        = ["selection_bg", "selection_bg"]

[foregrounds]
"ForegroundActive"   = "active"
"ForegroundInactive" = "inactive"
"ForegroundLink"     = "link"
"ForegroundNegative" = "negative"
"ForegroundNeutral"  = "neutral"
"ForegroundNormal"   = "foreground"
"ForegroundPositive" = "positive"
"ForegroundVisited"  = "visited"

[selection_foregrounds]
"ForegroundActive"   = "selection_fg"
"ForegroundInactive" = "selection_fg"
"ForegroundLink"     = "selection_fg"
"ForegroundNegative" = "selection_fg"
"ForegroundNeutral"  = "selection_fg"
"ForegroundNormal"   = "selection_fg"
"ForegroundPositive" = "selection_fg"
"ForegroundVisited"  = "selection_fg"