[flavour]
dark  = "mocha"
light = "latte"

[colors]
rosewater = "bright_red~yellow/300"
flamingo  = "bright_red"
pink      = "bright_magenta"
mauve     = "magenta"
red       = "red"
maroon    = "red~bright_yellow/300"
peach     = "bright_yellow"
yellow    = "yellow"
green     = "green"
teal      = "cyan"
sky       = "bright_cyan~blue/200"
sapphire  = "bright_cyan~blue/600"
blue      = "blue"
lavender  = "bright_blue"
text      = "fg"
subtext1  = "muted"
subtext0  = "bg/800"
overlay2  = "disabled"
overlay1  = "bg/600"
overlay0  = "separator"
surface2  = "border"
surface1  = "surface_alt"
surface0  = "surface"
base      = "bg"
mantle    = "panel"
crust     = "sunken"
