# Generated by scripts/generate-theme.py from theme/palette.toml — do not edit.
export THEME_RESET=$'\e[0m'
export THEME_SUDO=$'\e[38;2;243;139;168m'
export EZA_COLORS="di=38;2;61;174;233:ex=38;2;124;255;107:ln=38;2;26;188;156:*.md=38;2;253;188;75:*.toml=38;2;253;188;75:*.json=38;2;249;226;175:*.yml=38;2;250;179;135:*.yaml=38;2;250;179;135:*.lock=38;2;108;112;134:*.sh=38;2;124;255;107"
