[package]
name              = "git-discard"
version.workspace = true
description       = "Discard every change in the working tree"
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
clap.workspace        = true
gitkit.workspace      = true
gix.workspace         = true
workstation.workspace = true

[dev-dependencies]
tempfile.workspace = true