[package]
name                   = "dcloud"
version.workspace      = true
edition.workspace      = true
license.workspace      = true
publish.workspace      = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
ui-picker.workspace = true

anyhow                     = "1"
cap-std                    = "3"
configparser               = "3"
age.workspace              = true
chrono                     = { version = "0.4", features = ["serde"] }
chrono-tz                  = "0.10"
clap.workspace             = true
ui-file-explorer.workspace = true
filetime                   = "0.2"
fs2                        = "0.4"
globset                    = "0.4"
hmac                       = "0.12"
hostkit.workspace          = true
libc.workspace             = true
rusqlite                   = { version = "0.37", features = ["bundled"] }
serde.workspace            = true
serde_json.workspace       = true
sha2.workspace             = true
tar                        = { version = "0.4", features = ["xattr"] }
tempfile.workspace         = true
toml                       = "0.9"
uuid                       = { version = "1", features = ["v4", "serde"] }
walkdir                    = "2"
xattr                      = "1"
workstation.workspace      = true
zstd                       = { version = "0.13", features = ["zstdmt"] }
zeroize                    = "1"

[dev-dependencies]
testkit.workspace = true