---@class Mods
---@field PRIMARY string
---@field SECONDARY string
---@field UNIQUE_LEFT string
---@field UNIQUE_RIGHT string
---@field EDGE string
---@field SUPER_REV string
---@field SUPER_REV_2 string
---@field EDGE_REV string
---@field SPLITBELOW string
---@field UNIQUE_XOR string[]