use super::{Command, Completion, Param};
use std::collections::BTreeMap;

type Helpers = BTreeMap<String, String>;

pub fn script(tree: &Command) -> String {
    let program = tree.path.first().map(String::as_str).unwrap_or("dotfile");
    let function = name(tree);
    let mut helpers = Helpers::new();
    let mut parts = vec![format!(
        "#compdef {program}\n\n# Generated by `{program} --completions zsh`.\n"
    )];
    for command in tree.walk() {
        parts.push(function_body(command, &mut helpers));
    }
    parts.extend(helpers.into_values());
    parts.push(format!("if [ \"$funcstack[1]\" = \"{function}\" ]; then\n    {function} \"$@\"\nelse\n    compdef {function} {program}\nfi\n"));
    parts.join("\n")
}
fn name(c: &Command) -> String {
    format!("_{}", c.path.join("__"))
}
fn describe(s: &str) -> String {
    s.split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
        .replace('\\', "\\\\")
        .replace(':', "\\:")
        .replace('[', "\\[")
        .replace(']', "\\]")
}
fn quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}
fn arguments(specs: &[String], children: bool) -> String {
    let flags = if children { "-s -S -C" } else { "-s -S" };
    if specs.is_empty() {
        return format!("    _arguments {flags} && ret=0");
    }
    format!(
        "    _arguments {flags} \\\n        {} && ret=0",
        specs.join(" \\\n        ")
    )
}
fn function_body(c: &Command, helpers: &mut Helpers) -> String {
    if let Some(delegate) = &c.delegate {
        return format!(
            "{}() {{\n    (( $+functions[_{delegate}] )) && _{delegate} \"$@\"\n}}\n",
            name(c)
        );
    }
    let mut specs = Vec::new();
    let mut position = 0;
    for p in &c.params {
        if p.hidden {
            continue;
        }
        let action = action(c, p, helpers);
        let tag = describe(&p.name.replace('_', "-"));
        if p.kind == "option" {
            let spellings = p
                .opts
                .iter()
                .chain(&p.secondary)
                .cloned()
                .collect::<Vec<_>>();
            let exclusion = if p.standard() {
                "(- *)".to_string()
            } else if p.multiple {
                String::new()
            } else {
                let mut excluded = spellings.clone();
                excluded.extend(p.conflicts.iter().cloned());
                excluded.sort();
                excluded.dedup();
                format!("({})", excluded.join(" "))
            };
            let star = if p.multiple { "*" } else { "" };
            let help = describe(&p.help);
            let help = if help.is_empty() {
                help
            } else {
                format!("[{help}]")
            };
            for spelling in &spellings {
                let body = if p.metavar.is_empty() {
                    format!("{star}{exclusion}{spelling}{help}")
                } else {
                    let suffix = if spelling.starts_with("--") { "=" } else { "+" };
                    format!("{star}{exclusion}{spelling}{suffix}{help}:{tag}:{action}")
                };
                specs.push(quote(&body));
            }
        } else {
            position += 1;
            let index = if p.multiple {
                "*".into()
            } else {
                position.to_string()
            };
            let sep = if p.required || p.multiple { ":" } else { "::" };
            specs.push(quote(&format!("{index}{sep}{tag}:{action}")));
        }
    }
    let children = c
        .children
        .iter()
        .filter(|c| !c.hidden && c.name() != "help")
        .collect::<Vec<_>>();
    let mut lines = vec![
        format!("{}() {{", name(c)),
        "    local context state state_descr line ret=1".into(),
        "    typeset -A opt_args".into(),
    ];
    if !children.is_empty() {
        specs.extend(["'1: :->command'".into(), "'*:: :->argument'".into()]);
        lines.push(arguments(&specs, true));
        lines.extend([
            "    case $state in".into(),
            "        command)".into(),
            "            local -a commands".into(),
            "            commands=(".into(),
        ]);
        for child in &children {
            lines.push(format!(
                "                {}",
                quote(&format!("{}:{}", child.name(), describe(&child.help)))
            ));
        }
        lines.extend([
            "            )".into(),
            format!(
                "            _describe -t commands {} commands && ret=0",
                quote(&format!("{} command", c.label()))
            ),
            "            ;;".into(),
            "        argument)".into(),
            "            case $line[1] in".into(),
        ]);
        for child in &children {
            lines.push(format!(
                "                {}) {} && ret=0 ;;",
                std::iter::once(child.name())
                    .chain(child.aliases.iter().map(String::as_str))
                    .collect::<Vec<_>>()
                    .join("|"),
                name(child)
            ));
        }
        lines.extend([
            "            esac".into(),
            "            ;;".into(),
            "    esac".into(),
        ]);
    } else {
        lines.push(arguments(&specs, false));
    }
    lines.extend(["    return ret".into(), "}\n".into()]);
    lines.join("\n")
}
fn action(c: &Command, p: &Param, helpers: &mut Helpers) -> String {
    if let Some(completion) = &p.completion {
        return match completion {
            Completion::Call { source } => helper_for(&c.path[0], source, helpers),
            Completion::Files { pattern } if !pattern.is_empty() => {
                format!("_files -g {}", quote(pattern))
            }
            Completion::Files { .. } => "_files".into(),
            Completion::Dirs => "_files -/".into(),
            Completion::Pair { groups, names } => pair(&c.path[0], &p.name, groups, names, helpers),
        };
    }
    if !p.choices.is_empty() {
        let choices = p
            .choices
            .iter()
            .map(|choice| quote(choice))
            .collect::<Vec<_>>()
            .join(" ");
        if let Some(delimiter) = p.delimiter {
            return format!(
                "_values -s {} {} {choices}",
                quote(&delimiter.to_string()),
                quote(&p.name)
            );
        }
        return format!("({choices})");
    }
    if p.flag() == "--completions" {
        return "(zsh)".into();
    }
    String::new()
}

fn pair(
    program: &str,
    parameter: &str,
    groups: &str,
    names: &str,
    helpers: &mut Helpers,
) -> String {
    let name = format!("_{program}_complete_{}", parameter.replace('-', "_"));
    helpers.entry(name.clone()).or_insert_with(||format!("{name}() {{\n    local -a items\n    if compset -P '*='; then\n        items=(${{(f)\"$(_call_program {program}-values {program} __complete {names} ${{IPREFIX%=}} 2>/dev/null)\"}})\n        _describe -t values 'value' items\n    else\n        items=(${{(f)\"$(_call_program {program}-values {program} __complete {groups} 2>/dev/null)\"}})\n        _describe -t values 'group' items -S '=' -q\n    fi\n}}\n"));
    name
}

fn helper_for(program: &str, source: &str, helpers: &mut Helpers) -> String {
    let name = format!("_{program}_complete_{}", source.replace('-', "_"));
    helpers.entry(name.clone()).or_insert_with(||format!("{name}() {{\n    local -a items\n    items=(${{(f)\"$(_call_program {program}-values {program} __complete {source} 2>/dev/null)\"}})\n    (( $#items )) || return 1\n    _describe -t values '{source}' items\n}}\n"));
    name
}
