[package]
name              = "count"
version.workspace = true
description       = "Count items inside a directory"
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
clap.workspace = true
workstation    = { workspace = true, features = ["walk"] }

[dev-dependencies]
tempfile.workspace = true
