[package]
name              = "hwire"
version           = "0.1.0"
description       = "Latency and throughput between macie and archie"
edition.workspace = true
license.workspace = true

[dependencies]
clap.workspace        = true
crossterm.workspace   = true
hostkit.workspace     = true
ratatui.workspace     = true
serde_json.workspace  = true
tachyonfx.workspace   = true
workstation.workspace = true

[[bench]]
name    = "info"
harness = false