name = "Catppuccin Mocha"

[palette]
flamingo = "#f2cdcd"
pink     = "#f5c2e7"
mauve    = "#cba6f7"
red      = "#f38ba8"  # sudo
peach    = "#fab387"
yellow   = "#f9e2af"
orange   = "#fdbc4b" # (.venv), .toml,md...
green    = "#7cff6b"
teal     = "#1abc9c"  # dir
blue     = "#3daee9"  # system
lavender = "#b4befe"  # kde accent
text     = "#cdd6f4"
subtext  = "#bac2de"
overlay  = "#6c7086"  # separator
overlay2 = "#9399b2"  # kde inactive / disabled text
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base     = "#1e1e2e"
mantle   = "#181825"
crust    = "#11111b"

[roles]

# fastfetch
section_system   = "blue"
section_hardware = "peach"
section_desktop  = "mauve"
section_network  = "green"
separator        = "overlay"

# starship
prompt_python   = "orange"
prompt_git      = "green"
prompt_dir      = "teal"
prompt_duration = "yellow"
prompt_char     = "blue"

sudo = "red"  # shell

[terminal]
foreground           = "text" 
background           = "base"
cursor               = "flamingo"
cursor_text          = "base"
selection_foreground = "base"
selection_background = "flamingo"
url                  = "flamingo"

[terminal.ansi]
black          = "surface1"
red            = "red"
green          = "green"
yellow         = "yellow"
blue           = "blue"
magenta        = "pink"
cyan           = "teal"
white          = "subtext"
bright_black   = "surface2"
bright_red     = "red"
bright_green   = "green"
bright_yellow  = "yellow"
bright_blue    = "blue"
bright_magenta = "pink"
bright_cyan    = "teal"
bright_white   = "subtext"

[eza]
fi       = "subtext"   # fallback
di       = "blue"      # directories
ex       = "green"     # executables
ln       = "teal"      # symlinks

"*.toml" = "orange"
"*.json" = "yellow"
"*.lock" = "overlay"
"*.sh"   = "green"

[eza.categories]
image    = "mauve"
video    = "pink"
audio    = "teal"
archive  = "red"
document = "orange"
source   = "yellow"
config   = "peach"
markup   = "orange"
data     = "flamingo"
web      = "peach"
temp     = "overlay"
compiled = "overlay"

[kde]
accent = "lavender"

window_bg   = "base"
window_alt  = "mantle"
button_bg   = "surface0"
button_alt  = "surface1"
view_bg     = "base"
view_alt    = "mantle"
tooltip_bg  = "surface0"
tooltip_alt = "surface1"
header_bg   = "mantle"
header_alt  = "base"

selection_bg = "lavender"
selection_fg = "base"

foreground = "text"
inactive   = "overlay2"
active     = "lavender"
link       = "blue"
visited    = "mauve"
negative   = "red"
neutral    = "peach"
positive   = "green"
decoration = "lavender"

# window manager titlebar
wm_active_bg      = "base"
wm_active_fg      = "text"
wm_active_blend   = "text"
wm_inactive_bg    = "mantle"
wm_inactive_fg    = "overlay2"
wm_inactive_blend = "overlay2"
