[tokens]
sunken      = "bg/-100"
panel       = "bg/-50"
surface     = "bg/150"
surface_alt = "bg/250"
border      = "bg/400"
separator   = "bg/500"
disabled    = "bg/700"
muted       = "bg/900"
accent      = "bright_blue"
orange      = "bright_yellow~yellow/400"

[roles]

# fastfetch
section_system   = "blue"
section_hardware = "bright_yellow"
section_desktop  = "magenta"
section_network  = "green"
separator        = "separator"

# starship
prompt_python   = "orange"
prompt_git      = "green"
prompt_dir      = "cyan"
prompt_duration = "yellow"
prompt_char     = "blue"

sudo = "red" # shell

[terminal]
foreground           = "fg"
background           = "bg"
cursor               = "cursor"
cursor_text          = "cursor_text"
selection_foreground = "selection_fg"
selection_background = "selection_bg"
url                  = "bright_red"

[yazi]
primary = "magenta"

[eza]
fi = "muted" # fallback
di = "blue"  # directories
ex = "green" # executables
ln = "cyan"  # symlinks

"*.toml" = "orange"
"*.json" = "yellow"
"*.lock" = "separator"
"*.sh"   = "green"

[eza.categories]
image    = "magenta"
video    = "bright_magenta"
audio    = "cyan"
archive  = "red"
document = "orange"
source   = "yellow"
config   = "bright_yellow"
markup   = "orange"
data     = "bright_red"
web      = "bright_yellow"
temp     = "separator"
compiled = "separator"

[kde]
accent = "bright_blue"

window_bg   = "bg"
window_alt  = "panel"
button_bg   = "surface"
button_alt  = "surface_alt"
view_bg     = "bg"
view_alt    = "panel"
tooltip_bg  = "surface"
tooltip_alt = "surface_alt"
header_bg   = "panel"
header_alt  = "bg"

selection_bg = "magenta"
selection_fg = "contrast(magenta)"

foreground = "fg"
inactive   = "disabled"
active     = "bright_blue"
link       = "blue"
visited    = "magenta"
negative   = "red"
neutral    = "bright_yellow"
positive   = "green"
decoration = "bright_blue"

# window manager titlebar
wm_active_bg      = "bg"
wm_active_fg      = "fg"
wm_active_blend   = "fg"
wm_inactive_bg    = "panel"
wm_inactive_fg    = "disabled"
wm_inactive_blend = "disabled"

[konsole]
tab          = "bg"
focus_border = "sunken"
tab_activity = "fg"
