[roles]

# fastfetch
section_system   = "ansi_blue_text_on_canvas"
section_hardware = "bright_ansi_yellow_text_on_canvas"
section_desktop  = "ansi_magenta_text_on_canvas"
section_network  = "ansi_green_text_on_canvas"
separator        = "border_on_canvas"

# starship
prompt_python   = "bright_ansi_yellow_text_on_canvas"
prompt_git      = "ansi_green_text_on_canvas"
prompt_dir      = "ansi_cyan_text_on_canvas"
prompt_duration = "ansi_yellow_text_on_canvas"
prompt_char     = "ansi_blue_text_on_canvas"

sudo = "error_text_on_canvas" # shell

[terminal]
foreground           = "text_on_canvas"
background           = "canvas_bg"
cursor               = "cursor"
cursor_text          = "cursor_text"
selection_foreground = "on_primary"
selection_background = "primary_fill"
url                  = "info_text_on_canvas"

[eza]
fi = "muted_on_canvas"           # fallback
di = "ansi_blue_text_on_canvas"  # directories
ex = "ansi_green_text_on_canvas" # executables
ln = "ansi_cyan_text_on_canvas"  # symlinks

"*.toml" = "bright_ansi_yellow_text_on_canvas"
"*.json" = "ansi_yellow_text_on_canvas"
"*.lock" = "border_on_canvas"
"*.sh"   = "ansi_green_text_on_canvas"

[eza.categories]
image    = "ansi_magenta_text_on_canvas"
video    = "bright_ansi_magenta_text_on_canvas"
audio    = "ansi_cyan_text_on_canvas"
archive  = "ansi_red_text_on_canvas"
document = "bright_ansi_yellow_text_on_canvas"
source   = "ansi_yellow_text_on_canvas"
config   = "bright_ansi_yellow_text_on_canvas"
markup   = "bright_ansi_yellow_text_on_canvas"
data     = "bright_ansi_red_text_on_canvas"
web      = "bright_ansi_yellow_text_on_canvas"
temp     = "border_on_canvas"
compiled = "border_on_canvas"

[kde]
accent = "primary_fill"

window_bg   = "canvas_bg"
window_alt  = "panel_bg"
button_bg   = "surface_fill"
button_alt  = "panel_bg"
view_bg     = "canvas_bg"
view_alt    = "panel_bg"
tooltip_bg  = "surface_fill"
tooltip_alt = "panel_bg"
header_bg   = "panel_bg"
header_alt  = "canvas_bg"

selection_bg = "primary_fill"
selection_fg = "on_primary"

foreground = "ui.foreground"
inactive   = "disabled_on_canvas"
active     = "ui.primary"
link       = "ansi.normal.blue"
visited    = "ansi.normal.magenta"
negative   = "ansi.normal.red"
neutral    = "ansi.normal.yellow"
positive   = "ansi.normal.green"
decoration = "ui.primary"

# window manager titlebar
wm_active_bg      = "canvas_bg"
wm_active_fg      = "text_on_canvas"
wm_active_blend   = "text_on_canvas"
wm_inactive_bg    = "panel_bg"
wm_inactive_fg    = "disabled_on_panel"
wm_inactive_blend = "disabled_on_panel"

[konsole]
tab          = "canvas_bg"
focus_border = "focus_ring"
tab_activity = "text_on_canvas"