[roles]

# fastfetch
section_system   = "blue"
section_hardware = "bright_yellow"
section_desktop  = "magenta"
section_network  = "green"
separator        = "separator"

# starship
prompt_python   = "orange"
prompt_git      = "green"
prompt_dir      = "cyan"
prompt_duration = "yellow"
prompt_char     = "blue"

sudo = "error" # shell

[terminal]
foreground           = "foreground"
background           = "background"
cursor               = "cursor"
cursor_text          = "cursor_text"
selection_foreground = "selection_fg"
selection_background = "selection_bg"
url                  = "info"

[yazi]
primary = "primary"

[eza]
fi = "muted" # fallback
di = "blue"  # directories
ex = "green" # executables
ln = "cyan"  # symlinks

"*.toml" = "orange"
"*.json" = "yellow"
"*.lock" = "separator"
"*.sh"   = "green"

[eza.categories]
image    = "magenta"
video    = "bright_magenta"
audio    = "cyan"
archive  = "red"
document = "orange"
source   = "yellow"
config   = "bright_yellow"
markup   = "orange"
data     = "bright_red"
web      = "bright_yellow"
temp     = "separator"
compiled = "separator"

[kde]
accent = "primary"

window_bg   = "background"
window_alt  = "sidebar"
button_bg   = "surface"
button_alt  = "sidebar"
view_bg     = "background"
view_alt    = "sidebar"
tooltip_bg  = "surface"
tooltip_alt = "sidebar"
header_bg   = "sidebar"
header_alt  = "background"

selection_bg = "selection_bg"
selection_fg = "selection_fg"

foreground = "foreground"
inactive   = "disabled"
active     = "primary"
link       = "blue"
visited    = "magenta"
negative   = "error"
neutral    = "warning"
positive   = "success"
decoration = "primary"

# window manager titlebar
wm_active_bg      = "background"
wm_active_fg      = "foreground"
wm_active_blend   = "foreground"
wm_inactive_bg    = "sidebar"
wm_inactive_fg    = "disabled"
wm_inactive_blend = "disabled"

[konsole]
tab          = "background"
focus_border = "border"
tab_activity = "foreground"
