use crate::lang::Dialect;
use crate::scan::Comment;

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Kept {
    Shebang,
    Directive,
    License,
}

const OPENINGS: &[&str] = &[
    "type:",
    "noqa",
    "pylint:",
    "pyright:",
    "mypy:",
    "ruff:",
    "fmt:",
    "isort:",
    "nosec",
    "pragma:",
    "shellcheck ",
    "yamllint ",
    "nolint",
    "go:",
    "+build",
    "@ts-",
    "@flow",
    "@jsx",
    "@formatter:",
    "@vite-ignore",
    "eslint",
    "biome-ignore",
    "prettier-ignore",
    "deno-lint-ignore",
    "istanbul ignore",
    "c8 ignore",
    "v8 ignore",
    "swiftlint:",
    "ktlint-disable",
    "checkstyle:",
    "clang-format ",
    "iwyu pragma:",
    "vim:",
    "-*-",
    "-@",
    "$non-nls-",
    "webpackchunkname",
    "#__pure__",
    "rustfmt::skip",
];

const ANYWHERE: &[&str] = &[
    "do not edit",
    "code generated by",
    "sourcemappingurl",
    "spdx-license-identifier",
];

const LICENCES: &[&str] = &[
    "spdx-license-identifier",
    "copyright",
    "licensed under",
    "all rights reserved",
    "gnu general public",
    "mit license",
    "apache license",
];

pub fn kept(source: &[u8], comment: &Comment, dialect: Dialect, leading: bool) -> Option<Kept> {
    if comment.span.start == 0 && source.starts_with(b"#!") {
        return Some(Kept::Shebang);
    }
    let body = String::from_utf8_lossy(&source[comment.body.clone()]).to_lowercase();
    let opening = body
        .trim_start()
        .trim_start_matches(['*', '/'])
        .trim_start();
    if dialect == Dialect::Haskell && opening.starts_with('#') {
        return Some(Kept::Directive);
    }
    if OPENINGS.iter().any(|marker| opening.starts_with(marker)) {
        return Some(Kept::Directive);
    }
    if ANYWHERE.iter().any(|marker| body.contains(marker)) {
        return Some(Kept::Directive);
    }
    if leading && LICENCES.iter().any(|marker| body.contains(marker)) {
        return Some(Kept::License);
    }
    None
}
