[package]
name              = "gppf"
version.workspace = true
description       = "Stage everything, commit with the given message, and push"
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
clap.workspace        = true
gitkit.workspace      = true
workstation.workspace = true

[dev-dependencies]
tempfile.workspace = true