#!/usr/bin/env python3
"""Stamp the color theme from theme/palette.toml into every terminal config.

theme/palette.toml is the single source of truth. This renders it into:

  * kitty    — shared/kitty/.config/kitty/colors-mocha.conf   (included by kitty.conf)
  * konsole  — linux/kde/konsole/.local/share/konsole/Catppuccin-Mocha.colorscheme
  * fastfetch— config.jsonc $1..$5 constants + separator, and the arch.txt logo gradient
  * starship — the [palettes.mocha] block in starship.toml
  * zsh      — shared/zsh/.config/zsh/conf.d/03-theme.zsh (THEME_* prompt escapes)

In-place edits happen between `theme:<name>` / `theme:<name>:end` markers; the
rest of those files stays hand-editable. Fully generated files carry a
"do not edit" header.

Run by hand after editing the palette, or automatically from .githooks/pre-commit
when palette.toml is staged. Idempotent: reports what changed, no-ops otherwise.
"""
import os
import re
import sys
import tomllib

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
PALETTE = os.path.join(ROOT, "theme", "palette.toml")

GEN_HEADER = "Generated by scripts/generate-theme.py from theme/palette.toml — do not edit."


def load():
    with open(PALETTE, "rb") as f:
        return tomllib.load(f)


class Theme:
    def __init__(self, data):
        self.data = data
        self.palette = data["palette"]

    def hex(self, name):
        """Resolve a raw palette color name to '#rrggbb'."""
        try:
            return self.palette[name].lower()
        except KeyError:
            raise SystemExit(f"unknown palette color: {name}")

    def role(self, name):
        """Resolve a semantic role to '#rrggbb' via the palette."""
        try:
            return self.hex(self.data["roles"][name])
        except KeyError:
            raise SystemExit(f"unknown role: {name}")

    def rgb(self, hexval):
        h = hexval.lstrip("#")
        return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)

    def truecolor(self, hexval, bold=False):
        r, g, b = self.rgb(hexval)
        prefix = "1;" if bold else ""
        return f"\\u001b[{prefix}38;2;{r};{g};{b}m"


# ---------------------------------------------------------------------------
# file helpers
# ---------------------------------------------------------------------------

def write_if_changed(path, content, changed):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    old = None
    if os.path.exists(path):
        with open(path, encoding="utf-8") as f:
            old = f.read()
    if old != content:
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        changed.append(os.path.relpath(path, ROOT))


def edit_if_changed(path, transform, changed):
    with open(path, encoding="utf-8") as f:
        old = f.read()
    new = transform(old)
    if new != old:
        with open(path, "w", encoding="utf-8") as f:
            f.write(new)
        changed.append(os.path.relpath(path, ROOT))


def replace_between(text, name, new_lines, indent=""):
    """Replace the lines between `theme:<name>` and `theme:<name>:end` markers."""
    start = f"theme:{name}"
    end = f"theme:{name}:end"
    lines = text.split("\n")
    i = next((k for k, l in enumerate(lines) if end not in l and start in l), None)
    j = next((k for k, l in enumerate(lines) if end in l), None)
    if i is None or j is None or j < i:
        raise SystemExit(f"markers '{start}' / '{end}' not found in the target file")
    body = [indent + l if l else l for l in new_lines]
    return "\n".join(lines[: i + 1] + body + lines[j:])


# ---------------------------------------------------------------------------
# emitters
# ---------------------------------------------------------------------------

def gen_kitty(t, changed):
    term = t.data["terminal"]
    ansi = t.data["terminal"]["ansi"]
    slot = {  # ANSI role name -> kitty colorNN index
        "black": 0, "red": 1, "green": 2, "yellow": 3, "blue": 4, "magenta": 5,
        "cyan": 6, "white": 7, "bright_black": 8, "bright_red": 9,
        "bright_green": 10, "bright_yellow": 11, "bright_blue": 12,
        "bright_magenta": 13, "bright_cyan": 14, "bright_white": 15,
    }
    lines = [
        f"# {GEN_HEADER}",
        f"# {t.data['name']}",
        "",
        f"foreground              {t.hex(term['foreground'])}",
        f"background              {t.hex(term['background'])}",
        f"selection_foreground    {t.hex(term['selection_foreground'])}",
        f"selection_background    {t.hex(term['selection_background'])}",
        f"cursor                  {t.hex(term['cursor'])}",
        f"cursor_text_color       {t.hex(term['cursor_text'])}",
        f"url_color               {t.hex(term['url'])}",
        "",
    ]
    for name, idx in slot.items():
        lines.append(f"color{idx:<2} {t.hex(ansi[name])}")
    content = "\n".join(lines) + "\n"
    write_if_changed(
        os.path.join(ROOT, "shared/kitty/.config/kitty/colors-mocha.conf"),
        content, changed,
    )


def gen_konsole(t, changed):
    term = t.data["terminal"]
    ansi = t.data["terminal"]["ansi"]
    normal = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"]
    bright = ["bright_" + n for n in normal]

    def rgb_str(hexval):
        return "{},{},{}".format(*t.rgb(hexval))

    def block(section, hexval):
        return [f"[{section}]", f"Color={rgb_str(hexval)}", ""]

    out = []
    out += block("Background", t.hex(term["background"]))
    out += block("BackgroundIntense", t.hex(term["background"]))
    out += block("BackgroundFaint", t.hex(term["background"]))
    for i in range(8):
        out += block(f"Color{i}", t.hex(ansi[normal[i]]))
        out += block(f"Color{i}Intense", t.hex(ansi[bright[i]]))
        out += block(f"Color{i}Faint", t.hex(ansi[normal[i]]))
    out += block("Foreground", t.hex(term["foreground"]))
    out += block("ForegroundIntense", t.hex(term["foreground"]))
    out += block("ForegroundFaint", t.hex(term["foreground"]))
    out += [
        "[General]",
        "Blur=false",
        "ColorRandomization=false",
        f"Description={t.data['name']}",
        "Opacity=1",
        "Wallpaper=",
    ]
    header = f"# {GEN_HEADER}\n"
    content = header + "\n".join(out) + "\n"
    write_if_changed(
        os.path.join(
            ROOT, "linux/kde/konsole/.local/share/konsole/Catppuccin-Mocha.colorscheme"
        ),
        content, changed,
    )


def gen_fastfetch(t, changed):
    accents = [
        ("section_system", "$1"),
        ("section_hardware", "$2"),
        ("section_desktop", "$3"),
        ("section_network", "$4"),
    ]
    const_lines = []
    for i, (role, _) in enumerate(accents):
        hx = t.role(role)
        color = t.data["roles"][role]
        const_lines.append(f'"{t.truecolor(hx, bold=True)}", // {color} {hx}')
    sep_hex = t.role("separator")
    sep_name = t.data["roles"]["separator"]
    const_lines.append(f'"{t.truecolor(sep_hex)}" // {sep_name} {sep_hex}')

    path = os.path.join(ROOT, "shared/fastfetch/.config/fastfetch/config.jsonc")

    def transform(text):
        text = replace_between(text, "constants", const_lines, indent=" " * 6)
        lines = text.split("\n")
        for idx, l in enumerate(lines):
            if "theme:separator" in l:
                lines[idx] = re.sub(r"#[0-9a-fA-F]{6}", sep_hex, l)
        return "\n".join(lines)

    edit_if_changed(path, transform, changed)
    gen_fastfetch_logo(t, changed)


def gen_fastfetch_logo(t, changed):
    """Recolor arch.txt's ASCII art with a gradient over the 4 section accents."""
    stops = [
        t.rgb(t.role("section_system")),
        t.rgb(t.role("section_hardware")),
        t.rgb(t.role("section_desktop")),
        t.rgb(t.role("section_network")),
    ]
    segments = len(stops) - 1
    path = os.path.join(ROOT, "shared/fastfetch/.config/fastfetch/arch.txt")
    with open(path, encoding="utf-8") as f:
        raw = f.read().split("\n")
    # Drop a trailing empty element from a final newline; re-add it at the end.
    trailing_nl = raw and raw[-1] == ""
    if trailing_nl:
        raw = raw[:-1]

    art = [re.sub(r"\x1b\[[0-9;]*m", "", l) for l in raw]
    n = len(art)

    def lerp(a, b, u):
        return tuple(round(a[k] + (b[k] - a[k]) * u) for k in range(3))

    out = []
    for i, line in enumerate(art):
        pos = (i / (n - 1)) * segments if n > 1 else 0
        seg = min(int(pos), segments - 1)
        r, g, b = lerp(stops[seg], stops[seg + 1], pos - seg)
        out.append(f"\x1b[1;38;2;{r};{g};{b}m{line}")
    content = "\n".join(out) + "\x1b[0m"
    if trailing_nl:
        content += "\n"
    write_if_changed(path, content, changed)


def gen_starship(t, changed):
    prompt_roles = ("prompt_python", "prompt_git", "prompt_dir", "prompt_duration", "prompt_char")
    names = list(t.palette.keys())
    width = max(len(k) for k in names + list(prompt_roles))
    lines = [f"# {GEN_HEADER}", "[palettes.mocha]"]
    for name in names:
        lines.append(f"{name.ljust(width)} = '{t.hex(name)}'")
    lines.append("")
    for role in prompt_roles:
        lines.append(f"{role.ljust(width)} = '{t.role(role)}'")

    path = os.path.join(ROOT, "shared/starship/.config/starship.toml")
    edit_if_changed(path, lambda text: replace_between(text, "palette", lines), changed)


def gen_zsh(t, changed):
    r, g, b = t.rgb(t.role("sudo"))
    lines = [
        f"# {GEN_HEADER}",
        "export THEME_RESET=$'\\e[0m'",
        f"export THEME_SUDO=$'\\e[38;2;{r};{g};{b}m'",
    ]
    eza = t.data.get("eza", {})
    if eza:
        parts = []
        for code, color in eza.items():
            er, eg, eb = t.rgb(t.hex(color))
            parts.append(f"{code}=38;2;{er};{eg};{eb}")
        lines.append(f'export EZA_COLORS="{":".join(parts)}"')
    content = "\n".join(lines) + "\n"
    write_if_changed(
        os.path.join(ROOT, "shared/zsh/.config/zsh/conf.d/03-theme.zsh"),
        content, changed,
    )


def main():
    t = Theme(load())
    changed = []
    gen_kitty(t, changed)
    gen_konsole(t, changed)
    gen_fastfetch(t, changed)
    gen_starship(t, changed)
    gen_zsh(t, changed)
    if changed:
        print("theme: regenerated")
        for p in changed:
            print(f"  {p}")
    else:
        print("theme: already up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
