#!/usr/bin/env python3
"""Stamp the color theme from theme/palette.toml into every config that carries colors.

theme/palette.toml is the single source of truth. This renders it into:

  * kitty    — shared/kitty/colors-mocha.conf   (included by kitty.conf)
  * konsole  — linux/kde/konsole/share/Catppuccin-Mocha.colorscheme
  * fastfetch— config.jsonc $1..$5 constants + separator, and the arch.txt logo gradient
  * starship — the [palettes.mocha] block in starship.toml
  * zsh      — shared/zsh/conf.d/03-theme.zsh (THEME_* prompt escapes)
  * kde      — kdeglobals color scheme ([Colors:*], [WM], AccentColor) from [kde]
  * gtk      — gtk-3.0/gtk-4.0 colors.css so GTK apps match the KDE scheme
  * widgets  — retags Catppuccin colors in panel-colorizer presets + desktop-appletsrc
  * quicklaunch — the [theme] hex overrides in linux/common quicklaunch config.toml

In-place edits happen between `theme:<name>` / `theme:<name>:end` markers, or by
KConfig section, so the rest of those files stays hand-editable. Fully generated
files carry a "do not edit" header.

Run by hand after editing the palette, or automatically from .githooks/pre-commit
when palette.toml is staged. Idempotent: reports what changed, no-ops otherwise.
"""
import colorsys
import os
import re
import sys
import tomllib

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
PALETTE = os.path.join(ROOT, "theme", "palette.toml")
FONTS = os.path.join(ROOT, "theme", "fonts.toml")

GEN_HEADER = "Generated by scripts/generate-theme.py from theme/palette.toml — do not edit."

# Extensions per [eza.categories] group. eza (EZA_COLORS) matches by *.ext, so
# each category color is expanded to a glob per extension. Each ext lives in one
# category; explicit "*.ext" entries in [eza] override these.
EZA_CATEGORY_EXTS = {
    "image": "png jpg jpeg gif bmp tiff tif webp svg ico heic heif avif psd xcf cr2 nef dng raw",
    "video": "mp4 mkv mov avi wmv flv webm m4v mpg mpeg m2ts vob ogv 3gp f4v",
    "audio": "mp3 aac ogg oga opus m4a wma flac wav alac aiff aif ape wv mid midi",
    "archive": "zip tar gz tgz bz2 tbz xz txz zst 7z rar lz lzma lz4 lzo br cab cpio ar iso dmg deb rpm pkg apk jar war",
    "document": "pdf doc docx xls xlsx ppt pptx odt ods odp rtf epub mobi azw3 djvu tex ps eps",
    "source": "py pyi js mjs cjs ts tsx jsx rs go c h cpp cxx cc hpp hxx java kt kts rb php swift scala clj cljs hs ml mli lua pl pm r dart ex exs erl zig nim jl fs vb cs groovy gradle asm",
    "config": "toml yml yaml ini cfg conf config properties env editorconfig xml plist",
    "markup": "md markdown mdx rst adoc org txt text typ",
    "data": "json csv tsv parquet arrow db sqlite sqlite3 sql h5 hdf5 npy npz pkl feather proto graphql gql",
    "web": "html htm xhtml css scss sass less styl vue svelte astro",
    "temp": "tmp temp swp swo bak old orig cache log pid",
    "compiled": "o obj a so dylib dll lib class pyc pyo pyd beam elc wasm bc out exe",
}


def load():
    with open(PALETTE, "rb") as f:
        return tomllib.load(f)


def load_fonts():
    with open(FONTS, "rb") as f:
        return tomllib.load(f)


class Theme:
    def __init__(self, data, font_data):
        self.data = data
        self.palette = data["palette"]
        self.fonts = font_data["fonts"]
        self.font_applications = font_data.get("applications", {})

    def hex(self, name):
        """Resolve a raw palette color name to '#rrggbb'."""
        try:
            return self.palette[name].lower()
        except KeyError:
            raise SystemExit(f"unknown palette color: {name}")

    def role(self, name):
        """Resolve a semantic role to '#rrggbb' via the palette."""
        try:
            return self.hex(self.data["roles"][name])
        except KeyError:
            raise SystemExit(f"unknown role: {name}")

    def kde(self, name):
        """Resolve a [kde] role to '#rrggbb' via the palette."""
        try:
            return self.hex(self.data["kde"][name])
        except KeyError:
            raise SystemExit(f"unknown kde role: {name}")

    def color(self, name):
        """Resolve a name that is either a [kde] role or a raw palette color."""
        if name in self.data.get("kde", {}):
            return self.kde(name)
        return self.hex(name)

    def font(self, name):
        try:
            return self.fonts[name]
        except KeyError:
            raise SystemExit(f"unknown font role: {name}")

    def uses_fonts(self, application):
        enabled = self.font_applications.get(application, False)
        if not isinstance(enabled, bool):
            raise SystemExit(f"font application setting must be true or false: {application}")
        return enabled

    def rgb(self, hexval):
        h = hexval.lstrip("#")
        return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)

    def truecolor(self, hexval, bold=False):
        r, g, b = self.rgb(hexval)
        prefix = "1;" if bold else ""
        return f"\\u001b[{prefix}38;2;{r};{g};{b}m"


# ---------------------------------------------------------------------------
# file helpers
# ---------------------------------------------------------------------------

def write_if_changed(path, content, changed):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    old = None
    if os.path.exists(path):
        with open(path, encoding="utf-8") as f:
            old = f.read()
    if old != content:
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        changed.append(os.path.relpath(path, ROOT))


def edit_if_changed(path, transform, changed):
    with open(path, encoding="utf-8") as f:
        old = f.read()
    new = transform(old)
    if new != old:
        with open(path, "w", encoding="utf-8") as f:
            f.write(new)
        changed.append(os.path.relpath(path, ROOT))


def replace_between(text, name, new_lines, indent=""):
    """Replace the lines between `theme:<name>` and `theme:<name>:end` markers."""
    start = f"theme:{name}"
    end = f"theme:{name}:end"
    lines = text.split("\n")
    i = next((k for k, l in enumerate(lines) if end not in l and start in l), None)
    j = next((k for k, l in enumerate(lines) if end in l), None)
    if i is None or j is None or j < i:
        raise SystemExit(f"markers '{start}' / '{end}' not found in the target file")
    body = [indent + l if l else l for l in new_lines]
    return "\n".join(lines[: i + 1] + body + lines[j:])


def _ini_section_bounds(lines, header):
    """Return (start, end) line indices for a KConfig section. `start` is the
    header line; the body runs (start, end) up to the next section or EOF."""
    marker = f"[{header}]"
    start = next((k for k, l in enumerate(lines) if l == marker), None)
    if start is None:
        raise SystemExit(f"kdeglobals: section '{marker}' not found")
    end = start + 1
    while end < len(lines) and not lines[end].startswith("["):
        end += 1
    return start, end


def replace_ini_section(text, header, body_lines):
    """Replace a KConfig section's body in place, keeping its position, the rest
    of the file, and the original count of trailing blank lines."""
    lines = text.split("\n")
    start, end = _ini_section_bounds(lines, header)
    old_body = lines[start + 1:end]
    blanks = 0
    while old_body and old_body[-1] == "":
        blanks += 1
        old_body.pop()
    new_body = list(body_lines) + [""] * blanks
    return "\n".join(lines[:start + 1] + new_body + lines[end:])


def set_ini_key(text, header, key, value):
    """Set `key=value` within a KConfig section, inserting in alphabetical order
    if the key is absent."""
    lines = text.split("\n")
    start, end = _ini_section_bounds(lines, header)
    for k in range(start + 1, end):
        if lines[k].split("=", 1)[0] == key:
            lines[k] = f"{key}={value}"
            return "\n".join(lines)
    insert_at = end
    for k in range(start + 1, end):
        name = lines[k].split("=", 1)[0]
        if name and not lines[k].startswith("[") and name > key:
            insert_at = k
            break
    lines.insert(insert_at, f"{key}={value}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# emitters
# ---------------------------------------------------------------------------

def gen_kitty(t, changed):
    term = t.data["terminal"]
    ansi = t.data["terminal"]["ansi"]
    tabs = t.data["kitty"]["tabs"]
    slot = {  # ANSI role name -> kitty colorNN index
        "black": 0, "red": 1, "green": 2, "yellow": 3, "blue": 4, "magenta": 5,
        "cyan": 6, "white": 7, "bright_black": 8, "bright_red": 9,
        "bright_green": 10, "bright_yellow": 11, "bright_blue": 12,
        "bright_magenta": 13, "bright_cyan": 14, "bright_white": 15,
    }
    lines = [
        f"# {GEN_HEADER}",
        f"# {t.data['name']}",
        "",
        f"foreground              {t.hex(term['foreground'])}",
        f"background              {t.hex(term['background'])}",
        f"selection_foreground    {t.hex(term['selection_foreground'])}",
        f"selection_background    {t.hex(term['selection_background'])}",
        f"cursor                  {t.hex(term['cursor'])}",
        f"cursor_text_color       {t.hex(term['cursor_text'])}",
        f"url_color               {t.hex(term['url'])}",
        "",
    ]
    for name, idx in slot.items():
        lines.append(f"color{idx:<2} {t.hex(ansi[name])}")
    lines += [
        "",
        f"active_tab_foreground   {t.hex(tabs['active_foreground'])}",
        f"active_tab_background   {t.hex(tabs['active_background'])}",
        f"inactive_tab_foreground {t.hex(tabs['inactive_foreground'])}",
        f"inactive_tab_background {t.hex(tabs['inactive_background'])}",
        f"tab_bar_background      {t.hex(tabs['bar_background'])}",
    ]
    content = "\n".join(lines) + "\n"
    write_if_changed(
        os.path.join(ROOT, "shared/kitty/colors-mocha.conf"),
        content, changed,
    )


def gen_konsole(t, changed):
    term = t.data["terminal"]
    ansi = t.data["terminal"]["ansi"]
    normal = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"]
    bright = ["bright_" + n for n in normal]

    def rgb_str(hexval):
        return "{},{},{}".format(*t.rgb(hexval))

    def block(section, hexval):
        return [f"[{section}]", f"Color={rgb_str(hexval)}", ""]

    out = []
    out += block("Background", t.hex(term["background"]))
    out += block("BackgroundIntense", t.hex(term["background"]))
    out += block("BackgroundFaint", t.hex(term["background"]))
    for i in range(8):
        out += block(f"Color{i}", t.hex(ansi[normal[i]]))
        out += block(f"Color{i}Intense", t.hex(ansi[bright[i]]))
        out += block(f"Color{i}Faint", t.hex(ansi[normal[i]]))
    out += block("Foreground", t.hex(term["foreground"]))
    out += block("ForegroundIntense", t.hex(term["foreground"]))
    out += block("ForegroundFaint", t.hex(term["foreground"]))
    out += [
        "[General]",
        "Blur=false",
        "ColorRandomization=false",
        f"Description={t.data['name']}",
        "Opacity=1",
        "Wallpaper=",
    ]
    header = f"# {GEN_HEADER}\n"
    content = header + "\n".join(out) + "\n"
    write_if_changed(
        os.path.join(
            ROOT, "linux/kde/konsole/share/Catppuccin-Mocha.colorscheme"
        ),
        content, changed,
    )


def gen_fastfetch(t, changed):
    accents = [
        ("section_system", "$1"),
        ("section_hardware", "$2"),
        ("section_desktop", "$3"),
        ("section_network", "$4"),
    ]
    const_lines = []
    for i, (role, _) in enumerate(accents):
        hx = t.role(role)
        color = t.data["roles"][role]
        const_lines.append(f'"{t.truecolor(hx, bold=True)}", // {color} {hx}')
    sep_hex = t.role("separator")
    sep_name = t.data["roles"]["separator"]
    const_lines.append(f'"{t.truecolor(sep_hex)}" // {sep_name} {sep_hex}')

    path = os.path.join(ROOT, "shared/fastfetch/config.jsonc")

    def transform(text):
        text = replace_between(text, "constants", const_lines, indent=" " * 6)
        lines = text.split("\n")
        for idx, l in enumerate(lines):
            if "theme:separator" in l:
                lines[idx] = re.sub(r"#[0-9a-fA-F]{6}", sep_hex, l)
        return "\n".join(lines)

    edit_if_changed(path, transform, changed)
    gen_fastfetch_logo(t, changed)


def gen_fastfetch_logo(t, changed):
    """Recolor arch.txt's ASCII art with a gradient over the 4 section accents."""
    stops = [
        t.rgb(t.role("section_system")),
        t.rgb(t.role("section_hardware")),
        t.rgb(t.role("section_desktop")),
        t.rgb(t.role("section_network")),
    ]
    segments = len(stops) - 1
    path = os.path.join(ROOT, "shared/fastfetch/arch.txt")
    with open(path, encoding="utf-8") as f:
        raw = f.read().split("\n")
    # Drop a trailing empty element from a final newline; re-add it at the end.
    trailing_nl = raw and raw[-1] == ""
    if trailing_nl:
        raw = raw[:-1]

    art = [re.sub(r"\x1b\[[0-9;]*m", "", l) for l in raw]
    n = len(art)

    def lerp(a, b, u):
        return tuple(round(a[k] + (b[k] - a[k]) * u) for k in range(3))

    out = []
    for i, line in enumerate(art):
        pos = (i / (n - 1)) * segments if n > 1 else 0
        seg = min(int(pos), segments - 1)
        r, g, b = lerp(stops[seg], stops[seg + 1], pos - seg)
        out.append(f"\x1b[1;38;2;{r};{g};{b}m{line}")
    content = "\n".join(out) + "\x1b[0m"
    if trailing_nl:
        content += "\n"
    write_if_changed(path, content, changed)


def gen_starship(t, changed):
    prompt_roles = ("prompt_python", "prompt_git", "prompt_dir", "prompt_duration", "prompt_char")
    names = list(t.palette.keys())
    width = max(len(k) for k in names + list(prompt_roles))
    lines = [f"# {GEN_HEADER}", "[palettes.mocha]"]
    for name in names:
        lines.append(f"{name.ljust(width)} = '{t.hex(name)}'")
    lines.append("")
    for role in prompt_roles:
        lines.append(f"{role.ljust(width)} = '{t.role(role)}'")

    path = os.path.join(ROOT, "shared/starship/starship.toml")
    edit_if_changed(path, lambda text: replace_between(text, "palette", lines), changed)


def gen_zsh(t, changed):
    def esc(role):
        er, eg, eb = t.rgb(t.role(role))
        return f"$'\\e[38;2;{er};{eg};{eb}m'"

    lines = [
        f"# {GEN_HEADER}",
        "export THEME_RESET=$'\\e[0m'",
        f"export THEME_SUDO={esc('sudo')}",
        f"export THEME_GIT={esc('prompt_git')}",
        f"export THEME_DIR={esc('prompt_dir')}",
        f"export THEME_CHAR={esc('prompt_char')}",
    ]
    eza = dict(t.data.get("eza", {}))
    if eza:
        categories = eza.pop("categories", {})

        def ansi(color):
            er, eg, eb = t.rgb(t.hex(color))
            return f"38;2;{er};{eg};{eb}"

        parts = ["reset"]
        # file kinds (fi is the base fallback for every regular file)
        for kind in ("fi", "di", "ex", "ln", "pi", "so", "bd", "cd"):
            if kind in eza:
                parts.append(f"{kind}={ansi(eza[kind])}")
        # categories expand to a glob per extension
        for cat, color in categories.items():
            exts = EZA_CATEGORY_EXTS.get(cat)
            if exts is None:
                sys.stderr.write(f"theme: unknown [eza.categories] group '{cat}'\n")
                continue
            for ext in exts.split():
                parts.append(f"*.{ext}={ansi(color)}")
        # explicit "*.ext" overrides come last so they win
        for key, color in eza.items():
            if key.startswith("*"):
                parts.append(f"{key}={ansi(color)}")
        lines.append("unset LS_COLORS")
        lines.append(f'export EZA_COLORS="{":".join(parts)}"')
    content = "\n".join(lines) + "\n"
    write_if_changed(
        os.path.join(ROOT, "shared/zsh/conf.d/03-theme.zsh"),
        content, changed,
    )


def gen_obsidian(t, changed):
    values = dict(t.palette)
    for name in (
        "crust",
        "overlay",
        "mauve",
        "red",
        "peach",
        "orange",
        "yellow",
        "green",
        "teal",
        "blue",
        "pink",
    ):
        values[f"{name}_rgb"] = ", ".join(str(channel) for channel in t.rgb(t.hex(name)))
    red, green, blue = (channel / 255 for channel in t.rgb(t.hex("mauve")))
    hue, lightness, saturation = colorsys.rgb_to_hls(red, green, blue)
    values["mauve_h"] = str(round(hue * 360))
    values["mauve_s"] = f"{round(saturation * 100)}%"
    values["mauve_l"] = f"{round(lightness * 100)}%"
    values["mauve_hsl"] = f"{round(hue * 360)}, {round(saturation * 100)}%, {round(lightness * 100)}%"
    font_overrides = []
    if t.uses_fonts("obsidian"):
        general = t.font("general").replace("\\", "\\\\").replace('"', '\\"')
        nerd = t.font("nerd").replace("\\", "\\\\").replace('"', '\\"')
        font_overrides = [
            f'  --font-interface-theme: "{general}", sans-serif;',
            f'  --font-text-theme: "{general}", sans-serif;',
            f'  --font-monospace-theme: "{nerd}", ui-monospace, monospace;',
        ]
    values["font_overrides"] = "\n".join(font_overrides)
    if font_overrides:
        values["font_overrides"] += "\n"
    css = """
.theme-dark,
.theme-light {
  color-scheme: dark;
  --color-base-00: @crust@;
  --color-base-05: @mantle@;
  --color-base-10: @base@;
  --color-base-20: @surface0@;
  --color-base-25: @surface1@;
  --color-base-30: @surface2@;
  --color-base-35: @overlay@;
  --color-base-40: @overlay2@;
  --color-base-50: @subtext@;
  --color-base-60: @text@;
  --color-base-70: @lavender@;
  --color-base-100: @text@;
  --color-red: @red@;
  --color-red-rgb: @red_rgb@;
  --color-orange: @orange@;
  --color-orange-rgb: @orange_rgb@;
  --color-yellow: @yellow@;
  --color-yellow-rgb: @yellow_rgb@;
  --color-green: @green@;
  --color-green-rgb: @green_rgb@;
  --color-cyan: @teal@;
  --color-cyan-rgb: @teal_rgb@;
  --color-blue: @blue@;
  --color-blue-rgb: @blue_rgb@;
  --color-purple: @mauve@;
  --color-purple-rgb: @mauve_rgb@;
  --color-pink: @pink@;
  --color-pink-rgb: @pink_rgb@;
  --background-primary: @base@;
  --background-primary-alt: @mantle@;
  --background-secondary: @mantle@;
  --background-secondary-alt: @crust@;
  --background-modifier-form-field: @surface0@;
  --background-modifier-form-field-highlighted: @surface1@;
  --background-modifier-box-shadow: rgba(@crust_rgb@, 0.45);
  --background-modifier-success: rgba(@green_rgb@, 0.16);
  --background-modifier-error: rgba(@red_rgb@, 0.16);
  --background-modifier-error-hover: rgba(@red_rgb@, 0.24);
  --background-modifier-cover: rgba(@crust_rgb@, 0.72);
  --background-modifier-border: @surface0@;
  --background-modifier-border-hover: @surface1@;
  --background-modifier-border-focus: @mauve@;
  --background-modifier-hover: rgba(@mauve_rgb@, 0.1);
  --background-modifier-active-hover: rgba(@mauve_rgb@, 0.16);
  --text-normal: @text@;
  --text-muted: @subtext@;
  --text-faint: @overlay2@;
  --text-on-accent: @crust@;
  --text-on-accent-inverted: @crust@;
  --text-success: @green@;
  --text-warning: @yellow@;
  --text-error: @red@;
  --text-accent: @mauve@;
  --text-accent-hover: @lavender@;
  --interactive-normal: @surface0@;
  --interactive-hover: @surface1@;
  --interactive-accent: @mauve@;
  --interactive-accent-hover: @lavender@;
  --accent-h: @mauve_h@;
  --accent-s: @mauve_s@;
  --accent-l: @mauve_l@;
  --interactive-accent-hsl: @mauve_hsl@;
  --scrollbar-bg: transparent;
  --scrollbar-thumb-bg: @surface1@;
  --scrollbar-active-thumb-bg: @surface2@;
  --icon-color: @subtext@;
  --icon-color-hover: @text@;
  --icon-color-active: @mauve@;
  --icon-color-focused: @lavender@;
  --nav-item-color: @subtext@;
  --nav-item-color-hover: @text@;
  --nav-item-color-active: @text@;
  --nav-item-color-selected: @text@;
  --nav-item-background-hover: rgba(@mauve_rgb@, 0.1);
  --nav-item-background-active: rgba(@mauve_rgb@, 0.16);
  --nav-indentation-guide-color: @surface0@;
  --titlebar-background: @mantle@;
  --titlebar-background-focused: @mantle@;
  --titlebar-text-color: @subtext@;
  --titlebar-text-color-focused: @text@;
  --tab-container-background: @mantle@;
  --tab-background-active: @base@;
  --tab-text-color: @overlay2@;
  --tab-text-color-focused: @subtext@;
  --tab-text-color-focused-active: @text@;
  --tab-text-color-focused-active-current: @mauve@;
  --tab-outline-color: @surface0@;
  --ribbon-background: @mantle@;
  --ribbon-background-collapsed: @crust@;
  --status-bar-background: @mantle@;
  --status-bar-border-color: @surface0@;
  --divider-color: @surface0@;
  --divider-color-hover: @mauve@;
  --modal-background: @mantle@;
  --modal-border-color: @surface1@;
  --prompt-background: @mantle@;
  --prompt-border-color: @surface1@;
  --link-color: @blue@;
  --link-color-hover: @lavender@;
  --link-external-color: @teal@;
  --link-external-color-hover: @green@;
  --link-unresolved-color: @pink@;
  --link-unresolved-opacity: 0.8;
  --link-unresolved-decoration-color: @pink@;
  --tag-color: @mauve@;
  --tag-color-hover: @lavender@;
  --tag-background: rgba(@mauve_rgb@, 0.13);
  --tag-background-hover: rgba(@mauve_rgb@, 0.22);
  --tag-border-color: rgba(@mauve_rgb@, 0.3);
  --tag-border-color-hover: @mauve@;
  --blockquote-border-color: @mauve@;
  --blockquote-color: @subtext@;
  --code-background: @mantle@;
  --code-normal: @flamingo@;
  --code-comment: @overlay2@;
  --code-function: @blue@;
  --code-important: @red@;
  --code-keyword: @mauve@;
  --code-operator: @teal@;
  --code-property: @yellow@;
  --code-punctuation: @overlay2@;
  --code-string: @green@;
  --code-tag: @red@;
  --code-value: @peach@;
  --code-variable: @pink@;
  --h1-color: @mauve@;
  --h2-color: @blue@;
  --h3-color: @teal@;
  --h4-color: @green@;
  --h5-color: @yellow@;
  --h6-color: @peach@;
  --hr-color: @surface1@;
  --indentation-guide-color: @surface0@;
  --indentation-guide-color-active: @overlay@;
  --metadata-label-text-color: @overlay2@;
  --metadata-input-text-color: @text@;
  --metadata-divider-color: @surface0@;
  --metadata-property-background: @mantle@;
  --checkbox-color: @mauve@;
  --checkbox-color-hover: @lavender@;
  --checkbox-border-color: @overlay@;
  --checkbox-border-color-hover: @mauve@;
  --table-border-color: @surface0@;
  --table-header-background: @mantle@;
  --table-header-background-hover: @surface0@;
  --table-row-background-hover: rgba(@mauve_rgb@, 0.08);
  --embed-background: @mantle@;
  --embed-border-start: @mauve@;
  --canvas-background: @crust@;
  --canvas-card-label-color: @subtext@;
  --canvas-dot-pattern: @surface0@;
  --graph-line: @surface1@;
  --graph-node: @mauve@;
  --graph-node-focused: @lavender@;
  --graph-node-tag: @teal@;
  --graph-node-attachment: @peach@;
  --graph-node-unresolved: @overlay@;
  --text-highlight-bg: rgba(@yellow_rgb@, 0.22);
  --text-highlight-bg-active: rgba(@peach_rgb@, 0.3);
  --highlight-mix-blend-mode: normal;
@font_overrides@  --radius-s: 6px;
  --radius-m: 10px;
  --radius-l: 14px;
  --radius-xl: 20px;
}

body {
  --file-line-width: 780px;
  --file-folding-offset: 24px;
  --input-radius: var(--radius-m);
  --button-radius: var(--radius-m);
  --tab-radius-active: var(--radius-m) var(--radius-m) 0 0;
  --nav-item-radius: var(--radius-s);
}

::selection {
  background: rgba(@mauve_rgb@, 0.3);
  color: @text@;
}

.workspace,
.workspace-split.mod-root .view-content {
  background: @base@;
}

.workspace-tab-header-container {
  border-bottom: 1px solid @surface0@;
}

.workspace-tab-header.is-active {
  box-shadow: inset 0 -2px @mauve@;
}

.workspace-tab-header.is-active::before,
.workspace-tab-header.is-active::after {
  display: none;
}

.nav-file-title,
.nav-folder-title,
.menu-item,
.suggestion-item {
  transition: background-color 120ms ease, color 120ms ease;
}

.nav-file-title.is-active,
.nav-folder-title.is-active {
  font-weight: 600;
}

.markdown-rendered h1,
.markdown-rendered h2,
.markdown-rendered h3,
.markdown-rendered h4,
.markdown-rendered h5,
.markdown-rendered h6,
.markdown-source-view.mod-cm6 .cm-header {
  letter-spacing: -0.015em;
}

.markdown-rendered h1 {
  border-bottom: 1px solid @surface0@;
  padding-bottom: 0.35em;
}

.markdown-rendered blockquote {
  background: @mantle@;
  border-radius: 0 var(--radius-m) var(--radius-m) 0;
  margin-inline: 0;
  padding: 0.5em 1em;
}

.markdown-rendered code,
.cm-s-obsidian span.cm-inline-code {
  border: 1px solid @surface0@;
  border-radius: 5px;
  padding: 0.1em 0.35em;
}

.markdown-rendered pre {
  border: 1px solid @surface0@;
  border-radius: var(--radius-m);
  box-shadow: 0 8px 24px rgba(@crust_rgb@, 0.2);
}

.markdown-rendered pre code {
  border: 0;
  padding: 0;
}

.markdown-rendered table {
  border-collapse: separate;
  border-spacing: 0;
  overflow: hidden;
}

.markdown-rendered th:first-child {
  border-top-left-radius: var(--radius-s);
}

.markdown-rendered th:last-child {
  border-top-right-radius: var(--radius-s);
}

.callout {
  background: rgba(var(--callout-color), 0.1);
  border: 1px solid rgba(var(--callout-color), 0.3);
  border-radius: var(--radius-m);
}

.callout-title {
  font-weight: 650;
}

.callout[data-callout="note"],
.callout[data-callout="info"],
.callout[data-callout="todo"] {
  --callout-color: @blue_rgb@;
}

.callout[data-callout="abstract"],
.callout[data-callout="summary"],
.callout[data-callout="tldr"],
.callout[data-callout="tip"],
.callout[data-callout="hint"],
.callout[data-callout="important"] {
  --callout-color: @teal_rgb@;
}

.callout[data-callout="success"],
.callout[data-callout="check"],
.callout[data-callout="done"] {
  --callout-color: @green_rgb@;
}

.callout[data-callout="question"],
.callout[data-callout="help"],
.callout[data-callout="faq"],
.callout[data-callout="warning"],
.callout[data-callout="caution"],
.callout[data-callout="attention"] {
  --callout-color: @yellow_rgb@;
}

.callout[data-callout="failure"],
.callout[data-callout="fail"],
.callout[data-callout="missing"],
.callout[data-callout="danger"],
.callout[data-callout="error"],
.callout[data-callout="bug"] {
  --callout-color: @red_rgb@;
}

.callout[data-callout="example"] {
  --callout-color: @mauve_rgb@;
}

.callout[data-callout="quote"],
.callout[data-callout="cite"] {
  --callout-color: @overlay_rgb@;
}

.tag {
  border: 1px solid var(--tag-border-color);
  border-radius: 999px;
  font-weight: 550;
  padding-inline: 0.55em;
  text-decoration: none;
}

input[type="checkbox"] {
  border-radius: 4px;
}

button,
.clickable-icon,
.dropdown,
input,
textarea {
  transition: border-color 120ms ease, background-color 120ms ease, color 120ms ease;
}

button.mod-cta {
  color: @crust@;
  font-weight: 650;
}

::-webkit-scrollbar {
  width: 10px;
  height: 10px;
}

::-webkit-scrollbar-thumb {
  background-clip: padding-box;
  border: 3px solid transparent;
  border-radius: 999px;
}
""".lstrip()
    for name, value in values.items():
        css = css.replace(f"@{name}@", value)
    unresolved = re.findall(r"@[a-z0-9_]+@", css)
    if unresolved:
        raise SystemExit(f"unresolved Obsidian theme values: {', '.join(unresolved)}")
    directory = os.path.join(ROOT, "linux/common/obsidian/themes/Fredrir")
    write_if_changed(os.path.join(directory, "theme.css"), css, changed)
    manifest = """{
  "name": "Fredrir",
  "version": "1.0.0",
  "minAppVersion": "1.0.0",
  "author": "Fredrir"
}
"""
    write_if_changed(os.path.join(directory, "manifest.json"), manifest, changed)


# ---------------------------------------------------------------------------
# KDE / GTK
# ---------------------------------------------------------------------------

# KColorScheme group -> (background normal role, background alternate role) in
# [kde]. Every group shares the foreground/decoration roles below.
KDE_GROUPS = {
    "Colors:Window":           ("window_bg", "window_alt"),
    "Colors:Button":           ("button_bg", "button_alt"),
    "Colors:View":             ("view_bg", "view_alt"),
    "Colors:Tooltip":          ("tooltip_bg", "tooltip_alt"),
    "Colors:Complementary":    ("window_bg", "window_alt"),
    "Colors:Header":           ("header_bg", "header_alt"),
    "Colors:Header][Inactive": ("window_bg", "window_alt"),
    "Colors:Selection":        ("selection_bg", "selection_bg"),
}

# ForegroundX key -> [kde] role, shared by every group (alphabetical: matches
# how KConfig sorts keys on write).
KDE_FOREGROUNDS = [
    ("ForegroundActive", "active"),
    ("ForegroundInactive", "inactive"),
    ("ForegroundLink", "link"),
    ("ForegroundNegative", "negative"),
    ("ForegroundNeutral", "neutral"),
    ("ForegroundNormal", "foreground"),
    ("ForegroundPositive", "positive"),
    ("ForegroundVisited", "visited"),
]

# On the Selection group the plain-text foregrounds sit on the accent, so they
# flip to the dark selection_fg; the status colors stay put.
KDE_SELECTION_FG = {
    "ForegroundActive": "selection_fg",
    "ForegroundInactive": "selection_fg",
    "ForegroundNormal": "selection_fg",
}

# GTK @define-color name (without the `_breeze` suffix) -> [kde] role or palette
# color. kde-gtk-config normally derives this file from the active KDE scheme;
# generating it keeps the checked-in copy palette-driven regardless.
GTK_MAP = {
    "theme_fg_color": "foreground", "theme_text_color": "foreground",
    "theme_unfocused_fg_color": "foreground", "theme_unfocused_text_color": "foreground",
    "theme_button_foreground_normal": "foreground", "theme_button_foreground_active": "foreground",
    "theme_button_foreground_active_backdrop": "foreground", "theme_button_foreground_backdrop": "foreground",
    "theme_header_foreground": "foreground", "theme_header_foreground_backdrop": "foreground",
    "theme_titlebar_foreground": "foreground", "theme_titlebar_foreground_backdrop": "foreground",
    "tooltip_text": "foreground",
    "theme_bg_color": "window_bg", "theme_unfocused_bg_color": "window_bg",
    "theme_base_color": "view_bg", "theme_unfocused_base_color": "view_bg",
    "theme_unfocused_view_bg_color": "view_bg", "content_view_bg": "view_bg",
    "theme_button_background_normal": "button_bg", "theme_button_background_backdrop": "button_bg",
    "theme_header_background": "header_bg", "theme_titlebar_background": "header_bg",
    "theme_header_background_backdrop": "header_alt", "theme_header_background_light": "header_alt",
    "theme_titlebar_background_backdrop": "header_alt", "theme_titlebar_background_light": "header_alt",
    "tooltip_background": "tooltip_bg", "tooltip_border": "surface2",
    "theme_selected_bg_color": "selection_bg", "theme_hovering_selected_bg_color": "selection_bg",
    "theme_unfocused_selected_bg_color": "selection_bg", "theme_unfocused_selected_bg_color_alt": "selection_bg",
    "theme_selected_fg_color": "selection_fg", "theme_unfocused_selected_fg_color": "selection_fg",
    "theme_view_active_decoration_color": "decoration", "theme_view_hover_decoration_color": "decoration",
    "theme_button_decoration_focus": "decoration", "theme_button_decoration_focus_backdrop": "decoration",
    "theme_button_decoration_hover": "decoration", "theme_button_decoration_hover_backdrop": "decoration",
    "link_color": "link", "link_visited_color": "visited",
    "error_color": "negative", "error_color_backdrop": "negative",
    "success_color": "positive", "success_color_backdrop": "positive",
    "warning_color": "neutral", "warning_color_backdrop": "neutral",
    "borders": "surface1", "unfocused_borders": "surface1",
    # disabled / insensitive states dim to neutral surfaces
    "insensitive_base_color": "mantle", "insensitive_bg_color": "mantle",
    "insensitive_unfocused_bg_color": "mantle",
    "insensitive_base_fg_color": "overlay", "insensitive_fg_color": "overlay",
    "insensitive_selected_fg_color": "overlay", "insensitive_unfocused_fg_color": "overlay",
    "insensitive_unfocused_selected_fg_color": "overlay",
    "insensitive_selected_bg_color": "surface1", "insensitive_unfocused_selected_bg_color": "surface1",
    "insensitive_borders": "surface0", "unfocused_insensitive_borders": "surface0",
    "error_color_insensitive": "surface2", "error_color_insensitive_backdrop": "surface2",
    "success_color_insensitive": "surface2", "success_color_insensitive_backdrop": "surface2",
    "warning_color_insensitive": "surface2", "warning_color_insensitive_backdrop": "surface2",
    "theme_button_background_insensitive": "surface0",
    "theme_button_background_backdrop_insensitive": "surface0",
    "theme_button_foreground_insensitive": "overlay",
    "theme_button_foreground_backdrop_insensitive": "overlay",
    "theme_button_foreground_active_insensitive": "overlay",
    "theme_button_foreground_active_backdrop_insensitive": "overlay",
    "theme_button_decoration_focus_insensitive": "surface2",
    "theme_button_decoration_focus_backdrop_insensitive": "surface2",
    "theme_button_decoration_hover_insensitive": "surface2",
    "theme_button_decoration_hover_backdrop_insensitive": "surface2",
    "theme_header_foreground_insensitive": "overlay",
    "theme_header_foreground_insensitive_backdrop": "overlay",
    "theme_titlebar_foreground_insensitive": "overlay",
    "theme_titlebar_foreground_insensitive_backdrop": "overlay",
    "theme_unfocused_view_text_color": "overlay",
}

# Canonical Catppuccin colors (Mocha + Macchiato) -> palette color. Used to
# retag colors embedded in KDE widget config (panel-colorizer presets and the
# desktop-appletsrc) so they track the palette. Only these exact values are
# rewritten; unrecognised colors (widget placeholders, gradient defaults) stay.
CATPPUCCIN_TO_PALETTE = {
    "1e1e2e": "base", "181825": "mantle", "11111b": "crust", "cdd6f4": "text",
    "b4befe": "lavender", "cba6f7": "mauve", "f38ba8": "red", "fab387": "peach",
    "f9e2af": "yellow", "a6e3a1": "green", "94e2d5": "teal", "89b4fa": "blue",
    "f5c2e7": "pink", "f2cdcd": "flamingo", "6c7086": "overlay",
    "24273a": "base", "1e2030": "mantle", "181926": "crust", "cad3f5": "text",
    "b7bdf8": "lavender", "c6a0f6": "mauve", "ed8796": "red", "f5a97f": "peach",
    "eed49f": "yellow", "a6da95": "green", "8bd5ca": "teal", "8aadf4": "blue",
    "f5bde6": "pink", "f0c6c6": "flamingo", "6e738d": "overlay",
}


def gen_kde_colorscheme(t, changed):
    """Stamp the KDE/Qt color scheme into kdeglobals ([Colors:*], [WM], accent)."""
    def rgb_str(role):
        return "{},{},{}".format(*t.rgb(t.kde(role)))

    sections = {}
    for group, (bg, alt) in KDE_GROUPS.items():
        overrides = KDE_SELECTION_FG if group == "Colors:Selection" else {}
        body = [
            f"BackgroundAlternate={rgb_str(alt)}",
            f"BackgroundNormal={rgb_str(bg)}",
            f"DecorationFocus={rgb_str('decoration')}",
            f"DecorationHover={rgb_str('decoration')}",
        ]
        for key, role in KDE_FOREGROUNDS:
            body.append(f"{key}={rgb_str(overrides.get(key, role))}")
        sections[group] = body
    sections["WM"] = [
        f"activeBackground={rgb_str('wm_active_bg')}",
        f"activeBlend={rgb_str('wm_active_blend')}",
        f"activeForeground={rgb_str('wm_active_fg')}",
        f"inactiveBackground={rgb_str('wm_inactive_bg')}",
        f"inactiveBlend={rgb_str('wm_inactive_blend')}",
        f"inactiveForeground={rgb_str('wm_inactive_fg')}",
    ]

    path = os.path.join(ROOT, "linux/kde/plasma/kdeglobals")

    def transform(text):
        for header, body in sections.items():
            text = replace_ini_section(text, header, body)
        text = set_ini_key(text, "General", "AccentColor", rgb_str("accent"))
        text = set_ini_key(text, "General", "LastUsedCustomAccentColor", rgb_str("accent"))
        return text

    edit_if_changed(path, transform, changed)


def gen_gtk(t, changed):
    """Rewrite the GTK colors.css @define-color values from GTK_MAP so GTK apps
    match the KDE scheme."""
    line_re = re.compile(r"(@define-color\s+)(\S+)(\s+)(#[0-9a-fA-F]{6,8})(;.*)$")

    def transform(text):
        out = []
        for line in text.split("\n"):
            m = line_re.match(line)
            if m:
                var = m.group(2)
                base = var[:-7] if var.endswith("_breeze") else var
                if base in GTK_MAP:
                    line = f"{m.group(1)}{var}{m.group(3)}{t.color(GTK_MAP[base])}{m.group(5)}"
                else:
                    sys.stderr.write(f"theme: unmapped GTK color '{var}'\n")
            out.append(line)
        return "\n".join(out)

    for ver in ("gtk-3.0", "gtk-4.0"):
        edit_if_changed(
            os.path.join(ROOT, f"linux/common/gtk/{ver}/colors.css"),
            transform, changed,
        )


def gen_kde_widgets(t, changed):
    """Retag Catppuccin colors embedded in KDE widget config (panel-colorizer
    presets and the desktop-appletsrc) so they track the palette."""
    hex_map = {src: t.hex(role) for src, role in CATPPUCCIN_TO_PALETTE.items()}
    rgb_map = {}
    for src, role in CATPPUCCIN_TO_PALETTE.items():
        key = "{},{},{}".format(*t.rgb("#" + src))
        rgb_map[key] = "{},{},{}".format(*t.rgb(t.hex(role)))

    hex_re = re.compile(r"#([0-9a-fA-F]{8}|[0-9a-fA-F]{6})")
    rgb_line_re = re.compile(r"^([^=\[]+)=(\d{1,3},\d{1,3},\d{1,3})$")

    def remap_hex(text):
        def repl(m):
            tok = m.group(1).lower()
            return hex_map[tok] if len(tok) == 6 and tok in hex_map else m.group(0)
        return hex_re.sub(repl, text)

    presets = os.path.join(
        ROOT, "linux/kde/panel-colorizer/presets")
    if os.path.isdir(presets):
        for name in sorted(os.listdir(presets)):
            p = os.path.join(presets, name, "settings.json")
            if os.path.isfile(p) and os.path.getsize(p):
                edit_if_changed(p, remap_hex, changed)

    def remap_appletsrc(text):
        out = []
        for line in remap_hex(text).split("\n"):
            m = rgb_line_re.match(line)
            if m and m.group(2) in rgb_map:
                out.append(f"{m.group(1)}={rgb_map[m.group(2)]}")
            else:
                out.append(line)
        return "\n".join(out)

    edit_if_changed(
        os.path.join(ROOT, "linux/kde/plasma/plasma-org.kde.plasma.desktop-appletsrc"),
        remap_appletsrc, changed,
    )


def gen_quicklaunch(t, changed):
    keys = (
        ("accent", "accent"),
        ("background", "view_bg"),
        ("text", "foreground"),
        ("muted", "inactive"),
        ("selection", "selection_bg"),
    )
    width = max(len(k) for k, _ in keys)
    lines = [f"# {GEN_HEADER}"]
    for key, role in keys:
        lines.append(f'{key.ljust(width)} = "{t.kde(role)}"')
    path = os.path.join(
        ROOT, "linux/common/quicklaunch/config.toml")
    edit_if_changed(path, lambda text: replace_between(text, "quicklaunch", lines), changed)


def main():
    t = Theme(load(), load_fonts())
    changed = []
    gen_kitty(t, changed)
    gen_konsole(t, changed)
    gen_fastfetch(t, changed)
    gen_starship(t, changed)
    gen_zsh(t, changed)
    gen_obsidian(t, changed)
    gen_kde_colorscheme(t, changed)
    gen_gtk(t, changed)
    gen_kde_widgets(t, changed)
    gen_quicklaunch(t, changed)
    if changed:
        print("theme: regenerated")
        for p in changed:
            print(f"  {p}")
    else:
        print("theme: already up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
