name  = "Catppuccin Latte"
dark  = false
icons = "breeze"

[colors.primary]
background = "#eff1f5"
foreground = "#4c4f69"

[colors.cursor]
cursor = "#dd7878"
text   = "#eff1f5"

[colors.selection]
background = "#dd7878"
text       = "#eff1f5"

[colors.normal]
black   = "#bcc0cc"
red     = "#d20f39"
green   = "#40a02b"
yellow  = "#df8e1d"
blue    = "#1e66f5"
magenta = "#8839ef"
cyan    = "#179299"
white   = "#5c5f77"

[colors.bright]
black   = "#acb0be"
red     = "#dd7878"
green   = "#459042"
yellow  = "#fe640b"
blue    = "#7287fd"
magenta = "#ea76cb"
cyan    = "#30848f"
white   = "#4c4f69"