name = "Catppuccin Latte"
dark = false

[ui] # Mandatory
background = "#eff1f5" # Main background / Secondary-Sidebar- Colors
primary    = "#dd7878" # Active / Highlight / Primary- Colors
accent     = "#e6e8ee" # Sidebar Background / Support- Colors
surface    = "#d5d7df" # Dimmed / Border- Colors
foreground = "#4c4f69" # Text colors / brightest foreground

[ansi.normal] # Mandatory
black   = "#bcc0cc"
red     = "#d20f39"
green   = "#40a02b"
yellow  = "#df8e1d"
blue    = "#1e66f5"
magenta = "#8839ef"
cyan    = "#179299"
white   = "#5c5f77"

[ansi.bright] # Mandatory
black   = "#acb0be"
red     = "#dd7878"
green   = "#459042"
yellow  = "#fe640b"
blue    = "#7287fd"
magenta = "#ea76cb"
cyan    = "#30848f"
white   = "#4c4f69"