name = "Catppuccin Mocha"
dark = true

[ui] # Mandatory
background = "#1e1e2e" # Main background / Secondary-Sidebar- Colors
primary     = "#f2cdcd" # Active / Highlight / Primary- Colors
accent      = "#171726" # Sidebar Background / Support- Colors
surface     = "#343648" # Dimmed / Border- Colors
foreground  = "#cdd6f4" # Text colors / brightest foreground

[ansi.normal] # Mandatory
black   = "#45475a"
red     = "#f38ba8"
green   = "#7cff6b"
yellow  = "#f9e2af"
blue    = "#3daee9"
magenta = "#cba6f7"
cyan    = "#1abc9c"
white   = "#bac2de"

[ansi.bright] # Mandatory
black   = "#585b70"
red     = "#f2cdcd"
green   = "#a6e3a1"
yellow  = "#fab387"
blue    = "#b4befe"
magenta = "#f5c2e7"
cyan    = "#94e2d5"
white   = "#cdd6f4"
