[package]
name              = "gget"
version.workspace = true
description       = "Download a file or folder out of a GitHub repository"
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
clap.workspace        = true
tempfile.workspace    = true
workstation.workspace = true

[dev-dependencies]
testkit.workspace = true