[package]
name              = "path"
version.workspace = true
description       = "Repository-relative or home-relative path of a target"
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
clap.workspace        = true
workstation.workspace = true

[dev-dependencies]
testkit.workspace = true