[package]
name              = "dotfmt"
version.workspace = true
description       = "Command-line shell and visuals for dotfmt"
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
clap.workspace = true
workstation.workspace = true

[dev-dependencies]
testkit.workspace  = true
