
general {
    gaps_in = 3
    gaps_out = 6
    border_size = 2
    col.active_border = rgba(cba6f7cc)
    col.inactive_border = rgba(45475a00)

    resize_on_border = true
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 8

    active_opacity = 1.0
    inactive_opacity = 0.92

    blur {
        enabled = true
        size = 8
        passes = 2
        new_optimizations = true
        xray = false
        special = true
        popups = true
    }

    shadow {
        enabled = true
        range = 16
        render_power = 3
        color = rgba(1a1a2eee)
    }
}

animations {
    enabled = true

    bezier = myBezier, 0.05, 0.9, 0.1, 1.0

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

dwindle {
    pseudotile = true
    preserve_split = true
    smart_split = false
    smart_resizing = true
}
misc {
  force_default_wallpaper = 0
  disable_hyprland_logo = true
  font_family = "JetBrainsMono Nerd Font"
  focus_on_activate = true
  middle_click_paste = true
  vfr = true
  vrr = 1
  always_follow_on_dnd = true
close_special_on_empty = true
}
