exec-once = swaybg -i /home/fredrir/Downloads/wallhaven-6lkrow.png -m fill
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = hypridle

exec-once = systemd-run --user hyprpolkitagent
exec-once = gnome-keyring-daemon --start --components=secrets

exec-once = [workspace special:magic silent] kitty --class scratchterm
