exec-once = swaybg -i /home/fredrir/Downloads/r47ZMz7ZfAkSvvZ_Red-Forest-Torii_2_prob4.mp4 -m fill
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = hypridle

exec-once = systemd-run --user hyprpolkitagent

exec-once = elephant
exec-once = walker --gapplication-service

exec-once = waybar
exec-once = dunst
