windowrule = workspace special:magic silent, match:class scratchterm

windowrule {
  name = scratchterm
  match:class = scratchterm

  workspace = special:magic silent
  float = on
  center = on
  size = 75% 75%
  animation = popin 80%
  opacity = 0.92 0.85
}

windowrule {
  name = filechooser
  match:class = xdg-desktop-portal-gtk

  float = on
  center = on
  size = 75% 75%
  animation = popin 80%
  opacity = 0.92 0.85
}

workspace = w[t1], border:false, gapsout:0, gapsin:0
workspace = w[tg1], border:false, gapsout:0, gapsin:0

windowrule {
  name = yazi-overlay
  match:class = yazi-overlay

  float = on
  center = on
  size = 75% 75%
  animation = popin 80%
  opacity = 0.92 0.85
}

layerrule = blur on, match:namespace walker
layerrule = blur_popups on, match:namespace walker
layerrule = ignore_alpha 0.1, match:namespace walker
