windowrule = workspace special:magic silent, match:class scratchterm

windowrule {
  name = scratchterm
  match:class = scratchterm

  workspace = special:magic silent
  float = on
  size = 1200 800
  center = on
}

windowrule {
  name = filechooser
  match:class = xdg-desktop-portal-gtk

  float = on
  center = on
  size = 1200 800
}

workspace = w[t1], border:false, gapsout:0, gapsin:0
workspace = w[tg1], border:false, gapsout:0, gapsin:0

layerrule = blur on, match:namespace walker
layerrule = blur_popups on, match:namespace walker
layerrule = ignore_alpha 0.1, match:namespace walker
