windowrule {
  name = thunar 
  match:class = thunar 
  float = on
  center = on
  animation = popin 80%
  size = 1400 700
  opacity = 0.92 0.85
  border_size = 0
}

windowrule {
  name = yazi-overlay
    match:class = yazi-overlay
    float = on
    center = on
    size = 1400 700
    animation = popin 80%
    opacity = 0.92 0.85
}

windowrule {
  name = file-open
  match:class = xdg-desktop-portal-gtk
     float = on
    center = on
    size = 1400 700
    animation = popin 80%
    opacity = 0.92 0.85


}

workspace = w[t1], gapsout:0, gapsin:0, border:false
workspace = w[tg1], gapsout:0, gapsin:0, border:false


layerrule = blur on, match:namespace walker
layerrule = blur_popups on, match:namespace walker
layerrule = ignore_alpha 0.1, match:namespace walker

# Wlogout
layerrule = blur on, match:namespace logout_dialog
