source-file -q ~/.config/tmux/00-core.conf
source-file -q ~/.config/tmux/10-keys.conf
source-file -q ~/.config/tmux/20-copy.conf
source-file -q ~/.config/tmux/30-ui.conf
source-file -q ~/.config/tmux/90-plugins.conf

# Machine-specific overrides
source-file -q ~/.config/tmux/local.conf
