setw -g mode-keys vi
set -g status-keys emacs
setw -g wrap-search on
bind -N 'Enter copy mode and search scrollback' Enter copy-mode
bind -N 'Paste the latest tmux buffer' ] paste-buffer -p
bind -N 'Choose a saved clipboard buffer' b choose-buffer -Z

bind -T copy-mode-vi -N 'Begin selection' v send-keys -X begin-selection
bind -T copy-mode-vi -N 'Select a complete line' V send-keys -X select-line
bind -T copy-mode-vi -N 'Toggle rectangular selection' C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi -N 'Copy selection and return to work' y send-keys -X copy-selection-and-cancel
bind -T copy-mode-vi -N 'Copy selection and return to work' Enter send-keys -X copy-selection-and-cancel
bind -T copy-mode-vi -N 'Leave copy mode' Escape send-keys -X cancel
bind -T copy-mode-vi -N 'Leave copy mode' q send-keys -X cancel
bind -T copy-mode-vi -N 'Copy mouse selection and keep it highlighted' MouseDragEnd1Pane send-keys -X copy-selection-no-clear
bind -T copy-mode-vi -N 'Copy word and keep it highlighted' DoubleClick1Pane select-pane \; send-keys -X select-word \; run-shell -d 0.3 \; send-keys -X copy-selection-no-clear
bind -T copy-mode-vi -N 'Copy line and keep it highlighted' TripleClick1Pane select-pane \; send-keys -X select-line \; run-shell -d 0.3 \; send-keys -X copy-selection-no-clear
bind -T copy-mode-vi -N 'Jump to beginning of line' C-a send-keys -X start-of-line
bind -T copy-mode-vi -N 'Jump to end of line' C-e send-keys -X end-of-line
bind -T copy-mode-vi -N 'Move backward a word' M-b send-keys -X previous-word
bind -T copy-mode-vi -N 'Move forward a word' M-f send-keys -X next-word-end
bind -T copy-mode-vi -N 'Search forward incrementally' / command-prompt -i -p 'Find' 'send-keys -X search-forward-incremental "%%"'
bind -T copy-mode-vi -N 'Search backward incrementally' ? command-prompt -i -p 'Find backward' 'send-keys -X search-backward-incremental "%%"'

bind -N 'Jump to previous command prompt' Up copy-mode \; send-keys -X previous-prompt
bind -N 'Jump to next command prompt' Down copy-mode \; send-keys -X next-prompt
bind -T copy-mode-vi -N 'Previous command prompt' '[' send-keys -X previous-prompt
bind -T copy-mode-vi -N 'Next command prompt' ']' send-keys -X next-prompt
bind -T copy-mode-vi -N 'Beginning of previous command output' '{' send-keys -X previous-prompt -o
bind -T copy-mode-vi -N 'Beginning of next command output' '}' send-keys -X next-prompt -o

setw -g copy-mode-position-format '#[bold] COPY #[nobold] #{?selection_present,selected · ,}#{scroll_position}/#{history_size} · limit #{history_limit}#{?search_count, · #{search_count} matches,}'
setw -g copy-mode-line-numbers hybrid
